open_path:
  fields:
    bridge:
      required: true
      selector:
        device:
          integration: system_bridge
    path:
      required: true
      example: "C:\\test\\image.png"
      selector:
        text:
open_url:
  fields:
    bridge:
      required: true
      selector:
        device:
          integration: system_bridge
    url:
      required: true
      example: "https://www.home-assistant.io"
      selector:
        text:
send_keypress:
  fields:
    bridge:
      required: true
      selector:
        device:
          integration: system_bridge
    key:
      required: true
      example: "audio_play"
      selector:
        text:
send_text:
  fields:
    bridge:
      required: true
      selector:
        device:
          integration: system_bridge
    text:
      required: true
      example: "Hello world"
      selector:
        text:
