# Describes the format for available ADS services
mob_notify:
   description: 'Wysłanie powiadomienia push do aplikacji mobilnej.'
   fields:
     device_id:
       description: 'Identyfikator urządzenia.'
       example: 'mobile_ais_dom-'
     message:
       description: 'Tekst wiadomości'
       example: 'Dzwonek do drzwi.'
     title:
       description: 'Tytuł powiadomienia'
       example: 'Powiadomienie z AI-Speaker.'
     image:
       description: 'URL obrazu do wyświetlenia w powiadomieniu (plik max 1MB dostępny z Internetu)'
       example: 'http://ai-speaker.com/images/doorbell.jpg'
     priority:
       description: 'Priorytet wiadomości normal albo high'
       example: 'high'
     say:
       description: 'Czy wiadomość po odebraniu ma być przeczytana na telefonie.'
       example: True
     notification_id:
       description: 'Unikalny numer powiadomienia, jeśli wyślesz powiadomienie z tym samym numerem, to powiadomienie będzie nadpisywane.'
       example: '0'
     click_action:
       description: 'Nawigacja do widoku który mamy zdefiniowany w aplikacji np.: /lovelace/camera lub otwarcie strony internetowej o dowolnym adresie URL, np.: https://ai-speaker.com'
       example: '/lovelace/0'

mob_request:
   description: 'Wysłanie komendy (zapytania/żądania) do aplikacji mobilnej. Ta usługa wymaga aplikacji AIS dom w wersji 1.3.0 lub nowszej.'
   fields:
     device_id:
       description: 'Identyfikator urządzenia.'
       example: 'mobile_ais_dom-'
     request:
       description: 'Komenda np.: locationUpdate, micOn'
       example: 'micOn'
     data:
       description: 'Opcjonalne dane komendy'
       example: '{}'

check_local_ip:
  description: 'Sprawdzenie lokalnego IP bramki i ustawienie go jako wartość encji sensor.internal_ip_address. Ta usługa wykonaywana jest automatycznie przy starcie urządzenia.'

check_night_mode:
  description: 'Sprawdzenie czy został włączony tryb nocny jeżeli tak to zmieniamy temat w aplikacji i redukujemy głośność. Ta usługa wykonaywana jest co minutę.'

on_new_iot_device_selection:
  description: 'Ustalenie nazwy nowododawanego urządzenia. Ta usługa wykonaywana jest automaycznie podczas dodawania nowego urządzenia.'
  fields:
    iot:
      description: 'Model urządzenia.'
      example: 's20'

prepare_remote_menu:
  description: 'Przygotowanie menu dostępnego z pilota na podstawie grup/encji w systemie. Ta usługa wykonywana jest automatycznie po uruchomieniu systemu oraz po wykryciu/dodaniu nowych komponentów.'

process:
  description: 'Zamiana tekstu na komendę do wykonania.'
  fields:
    text:
      description: 'Tekst pynia/komendy.'
      example: 'Włącz radio RMF'

process_code:
  description: 'Przetwarzanie kodu z klawiatury/pilota. Ta usługa wykonywana jest automatycznie po otrzymaniu kodu z klawiatury/pilota.'
  fields:
    text:
      description: 'Wiadomość z kodem z pilota oraz akcją (0 - down, 1 - up, 2 - hold)'
      example: '{"text": "{\"KeyCode\": 92, \"Action\": \"0\"}"} '

process_command_from_frame:
  description: 'Przetwarzanie wiadomości/komendy otrzymanej z systemu Android.'
  fields:
    data:
      description: 'Przykładowy komunikat o zmianie adresu IP.'
      example: '{"topic": "ais/ip_state_change_info", "payload": "{\"ip\": \"192.168.1.1\"}"}'

publish_command_to_frame:
  description: 'Publikowanie komendy do systemu Android.'
  fields:
    key:
      description: 'Akcja do wykonania.'
      example: 'playAudio'
    val:
      description: 'Wiadomość / dane do akcji.'
      example: 'https://test/audio.mp3'

say_in_browser:
  description: 'Wysłanie tekstu do przeczytania w przeglądarce'
  fields:
    text:
      description: 'Tekst do przeczytania przez przeglądarkę'
      example: 'Cześć, tu przeglądarka'

say_it:
  description: 'Zamiana tekstu na mowę, czytanie tekstu. Za pomocą mechanizmu TTS w systemie Android na bramce.'
  fields:
    text:
      description: 'Tekst do przeczytania.'
      example: 'Cześć, jak się masz'
    img:
      description: 'URL zdjęcia do wyświetlenia.'
      example: 'http://ai-speaker.com/images/logo_ais.png'

set_context:
  description: 'Ustawienie kontekstu w jakim jest konwersacja z asystentem'
  fields:
    text:
      description: 'Kontekst do ustawienia'
      example: 'youtube'

welcome_home:
  description: 'Głosowy komunikat powitalny. Akcja wykonywana jest automatycznie podczas uruchomienia systemu.'

switch_ui:
  description: 'Przełączenie interfejsu odtwarzacza na wybrany tryb YouTube Spotify Radio Podcast'
  fields:
    mode:
      description: 'Tryb do ustawienia'
      example: 'Radio'