update:
  fields:
    account:
      required: true
      example: "steve@apple.com"
      selector:
        text:

play_sound:
  fields:
    account:
      required: true
      example: "steve@apple.com"
      selector:
        text:
    device_name:
      required: true
      example: "stevesiphone"
      selector:
        text:

display_message:
  fields:
    account:
      required: true
      example: "steve@apple.com"
      selector:
        text:
    device_name:
      required: true
      example: "stevesiphone"
      selector:
        text:
    message:
      required: true
      example: "Hey Steve !"
      selector:
        text:
    sound:
      selector:
        boolean:

lost_device:
  fields:
    account:
      required: true
      example: "steve@apple.com"
      selector:
        text:
    device_name:
      required: true
      example: "stevesiphone"
      selector:
        text:
    number:
      required: true
      example: "+33450020100"
      selector:
        text:
    message:
      required: true
      example: "Call me"
      selector:
        text:

next_media:
  target:
    entity:
      integration: icloud
      domain: camera
  fields:
    mode:
      required: false
      default: false
      selector:
        boolean:
