# Describes the format for available image processing services

scan:
  description: Process an image immediately.
  fields:
    entity_id:
      description: Name(s) of entities to scan immediately.
      example: "image_processing.alpr_garage"
