get_series:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: sonarr

get_queue:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: sonarr
