# Describes the format for available humidifier services

set_preset_mode:
  description: Set preset mode for humidifier device.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: 'humidifier.bedroom'
    preset_mode:
      description: New value of preset mode
      example: 'away'
set_humidity:
  description: Set target humidity of humidifier device.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: 'humidifier.bedroom'
    humidity:
      description: New target humidity for humidifier device.
      example: 50
set_fan_mode:
  description: Set fan operation for humidifier device.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: 'humidifier.bedroom'
    fan_mode:
      description: New value of fan mode.
      example: On Low
set_humidifier_mode:
  description: Set operation mode for humidifier device.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: 'humidifier.bedroom'
    humidifier_mode:
      description: New value of operation mode.
      example: humidify

turn_on:
  description: Turn humidifier device on.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: 'humidifier.bedroom'

turn_off:
  description: Turn humidifier device off.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: 'humidifier.bedroom'
