xiaomi_remote_control_start:
  description: Start remote control of the vacuum cleaner. You can then move it with `remote_control_move`, when done call `remote_control_stop`.
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.xiaomi_vacuum_cleaner"

xiaomi_remote_control_stop:
  description: Stop remote control mode of the vacuum cleaner.
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.xiaomi_vacuum_cleaner"

xiaomi_remote_control_move:
  description: Remote control the vacuum cleaner, make sure you first set it in remote control mode with `remote_control_start`.
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.xiaomi_vacuum_cleaner"
    velocity:
      description: Speed, between -0.29 and 0.29.
      example: "0.2"
    rotation:
      description: Rotation, between -179 degrees and 179 degrees.
      example: "90"
    duration:
      description: Duration of the movement.
      example: "1500"

xiaomi_remote_control_move_step:
  description: Remote control the vacuum cleaner, only makes one move and then stops.
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.xiaomi_vacuum_cleaner"
    velocity:
      description: Speed, between -0.29 and 0.29.
      example: "0.2"
    rotation:
      description: Rotation, between -179 degrees and 179 degrees.
      example: "90"
    duration:
      description: Duration of the movement.
      example: "1500"

xiaomi_clean_zone:
  description: Start the cleaning operation in the selected areas for the number of repeats indicated.
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.xiaomi_vacuum_cleaner"
    zone:
      description: Array of zones. Each zone is an array of 4 integer values.
      example: "[[23510,25311,25110,26362]]"
    repeats:
      description: Number of cleaning repeats for each zone between 1 and 3.
      example: "1"
