get_movies:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: radarr

get_queue:
  fields:
    entry_id:
      required: true
      selector:
        config_entry:
          integration: radarr
