disable:
  name: Disable
  description: Disable configured Pi-hole(s) for an amount of time
  target:
    entity:
      integration: pi_hole
      domain: switch
  fields:
    duration:
      name: Duration
      description: Time that the Pi-hole should be disabled for
      example: "00:00:15"
      selector:
        text:
