order:
  name: Order
  description: Places a set of orders with Dominos Pizza.
  fields:
    order_entity_id:
      name: Order Entity
      description: The ID (as specified in the configuration) of an order to place. If provided as an array, all of the identified orders will be placed.
      example: dominos.medium_pan
      selector:
        text:
