alarm_sound:
  target:
    entity:
      integration: ezviz
      domain: camera
  fields:
    level:
      required: true
      example: 0
      default: 0
      selector:
        number:
          min: 0
          max: 2
          step: 1
          mode: box
ptz:
  target:
    entity:
      integration: ezviz
      domain: camera
  fields:
    direction:
      required: true
      example: "up"
      default: "up"
      selector:
        select:
          options:
            - "up"
            - "down"
            - "left"
            - "right"
    speed:
      required: true
      example: 5
      default: 5
      selector:
        number:
          min: 1
          max: 9
          step: 1
          mode: box
set_alarm_detection_sensibility:
  target:
    entity:
      integration: ezviz
      domain: camera
  fields:
    level:
      required: true
      example: 3
      default: 3
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: box
    type_value:
      required: true
      example: "0"
      default: "0"
      selector:
        select:
          options:
            - "0"
            - "3"
sound_alarm:
  target:
    entity:
      integration: ezviz
      domain: camera
  fields:
    enable:
      required: true
      example: 1
      default: 1
      selector:
        number:
          min: 1
          max: 2
          step: 1
          mode: box
wake_device:
  target:
    entity:
      integration: ezviz
      domain: camera
