# Describes the format for available remote services

turn_on:
  description: Semds the Power On Command

  fields:
    entity_id:
      description: Name(s) of entities to turn on
      example: 'remote.family_room'
    activity:
      description: Activity ID or Activity Name to start
      example: 'BedroomTV'

turn_off:
  description: Sends the Power Off Command

  fields:
    entity_id:
      description: Name(s) of entities to turn off
      example: 'remote.family_room'

send_command:
  description: Semds a single command to a single device

  fields:
    entity_id:
      description: Name(s) of entities to send command from
      example: 'remote.family_room'
    device:
      description: Device ID to send command to
      example: '32756745'
    command:
      description: Command to send
      example: 'Play'

harmony_sync:
  description: Syncs the remote's configuration

  fields:
    entity_id:
      description: Name(s) of entities to sync
      example: 'remote.family_room'
