beolink_join:
  name: Beolink join
  description: Join a Beolink experience.
  target:
    entity:
      integration: bangolufsen
      domain: media_player
    device:
      integration: bangolufsen
  fields:
    beolink_jid:
      name: Beolink JID
      description: Manually specify Beolink JID to join.
      required: false
      example: 1111.2222222.33333333@products.bang-olufsen.com
      selector:
        text:

beolink_expand:
  name: Beolink expand
  description: Expand current Beolink experience.
  target:
    entity:
      integration: bangolufsen
      domain: media_player
    device:
      integration: bangolufsen
  fields:
    beolink_jids:
      name: Beolink JIDs
      description: Specify which Beolink JIDs will join current Beolink experience.
      required: true
      example: >-
        [
          1111.2222222.33333333@products.bang-olufsen.com,
          4444.5555555.66666666@products.bang-olufsen.com
        ]
      selector:
        object:

beolink_unexpand:
  name: Beolink unexpand
  description: Unexpand from current Beolink experience.
  target:
    entity:
      integration: bangolufsen
      domain: media_player
    device:
      integration: bangolufsen
  fields:
    beolink_jids:
      name: Beolink JIDs
      description: Specify which Beolink JIDs will leave from current Beolink experience.
      required: true
      example: >-
        [
          1111.2222222.33333333@products.bang-olufsen.com,
          4444.5555555.66666666@products.bang-olufsen.com
        ]
      selector:
        object:

beolink_leave:
  name: Beolink leave
  description: Leave a Beolink experience.
  target:
    entity:
      integration: bangolufsen
      domain: media_player
    device:
      integration: bangolufsen

beolink_allstandby:
  name: Beolink allstandby
  description: Set all Connected Beolink devices to standby.
  target:
    entity:
      integration: bangolufsen
      domain: media_player
    device:
      integration: bangolufsen

beolink_set_volume:
  name: Beolink set volume
  description: Set a volume level for all connected Beolink devices.
  target:
    entity:
      integration: bangolufsen
      domain: media_player
    device:
      integration: bangolufsen
  fields:
    volume_level:
      name: Volume level
      description: Specify the volume level.
      required: true
      example: 0.4
      selector:
        text:

beolink_leader_command:
  name: Beolink leader command
  description: Send a media_player command to Beolink leader.
  target:
    entity:
      integration: bangolufsen
      domain: media_player
    device:
      integration: bangolufsen
  fields:
    command:
      name: Command
      description: Specify the media_player command.
      required: true
      example: "set_volume_level"
      selector:
        select:
          options:
            - "set_volume_level"
            - "media_seek"
            - "mute_volume"
            - "select_source"
            - "volume_up"
            - "volume_down"
            - "media_play_pause"
            - "media_pause"
            - "media_play"
            - "media_stop"
            - "media_next_track"
            - "media_previous_track"
            - "toggle"
    parameter:
      name: Parameter
      description: Specify the media_player command's parameter.
      required: false
      example: 0.4
      selector:
        text:

overlay_audio:
  name: Overlay audio
  description: |
    Overlay audio over any currently playing audio.
    TTS is generated by Bang & Olufsen and is limited to 100 unique messages a day.
    Generated TTS messages are cached for 24 hours.
  target:
    entity:
      integration: bangolufsen
      domain: media_player
    device:
      integration: bangolufsen
  fields:
    uri:
      name: URI
      description: Specify the audio to play.
      required: false
      selector:
        text:
    absolute_volume:
      name: Absolute volume
      description: Specify an absolute volume for the overlay.
      required: false
      example: 40
      selector:
        number:
          min: 0
          max: 100
    volume_offset:
      name: Volume offset
      description: Specify a volume offset to be added to the current volume level.
      required: false
      example: 10
      selector:
        number:
          min: 0
          max: 100
    tts:
      name: Text to speech
      description: Specify a string to be converted to a TTS message.
      required: false
      example: This is a test
      selector:
        text:
    tts_language:
      name: Text to speech language
      description: Specify TTS language.
      required: false
      example: en-us
      selector:
        text:
