sudo: false
dist: xenial
addons:
  apt:
    sources:
      - sourceline: "ppa:jonathonf/ffmpeg-4"
    packages:
      - libudev-dev
      - libavformat-dev
      - libavcodec-dev
      - libavdevice-dev
      - libavutil-dev
      - libswscale-dev
      - libswresample-dev
      - libavfilter-dev
matrix:
  fast_finish: true
  include:
    - python: "3.6.1"
      env: TOXENV=lint
    - python: "3.6.1"
      env: TOXENV=pylint PYLINT_ARGS=--jobs=0
    - python: "3.6.1"
      env: TOXENV=typing
    - python: "3.6.1"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37

cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit
install: pip install -U tox
language: python
script: travis_wait 50 tox --develop
