sudo: false
addons:
  apt:
    packages:
      - libudev-dev
matrix:
  fast_finish: true
  include:
    - python: "3.5.3"
      env: TOXENV=lint
    - python: "3.5.3"
      env: TOXENV=pylint
    # - python: "3.5"
    #   env: TOXENV=typing
    - python: "3.5.3"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    # - python: "3.6-dev"
    #   env: TOXENV=py36
  # allow_failures:
  #   - python: "3.5"
  #     env: TOXENV=typing

cache:
  directories:
    - $HOME/.cache/pip
install: pip install -U tox coveralls
language: python
script: travis_wait 30 tox --develop
services:
  - docker
before_deploy:
  - docker pull lokalise/lokalise-cli
deploy:
  skip_cleanup: true
  provider: script
  script: script/travis_deploy
  on:
    branch: dev
after_success: coveralls
