# Describes the services for the Kaleidescape integration

send_volume_level:
  target:
    entity:
      domain: media_player
  fields:
    level:
      required: true
      example: 0.5
      selector:
        number:
          min: 0
          max: 1
          step: 0.01

send_volume_muted:
  target:
    entity:
      domain: media_player
  fields:
    muted:
      required: true
      example: true
      selector:
        boolean:
