add_bonus_time:
  fields:
    bonus_time:
      required: true
      example: 30
      selector:
        number:
          min: -1
          max: 1440
          unit_of_measurement: minutes
          mode: box
    config_entry_id:
      required: true
      example: 1234567890abcdef1234567890abcdef
      selector:
        config_entry:
          integration: nintendo_parental_controls
    device_id:
      required: true
      example: 1234567890abcdef1234567890abcdef
      selector:
        device:
          integration: nintendo_parental_controls
