change_association:
  description: Change an association in the Z-Wave network.
  fields:
    association:
      description: Specify add or remove assosication
    node_id:
      description: Node id of the node to set association for.
    target_node_id:
      description: Node id of the node to associate to.
    group:
      description: Group number to set association for.
    instance:
      description: (Optional) Instance of association. Defaults to 0.

add_node:
  description: Add a new node to the Z-Wave network. Refer to OZW.log for details.

add_node_secure:
  description: Add a new node to the Z-Wave network with secure communications. Node must support this, and network key must be set. Refer to OZW.log for details.

cancel_command:
  description: Cancel a running Z-Wave controller command. Use this to exit add_node, if you wasn't going to use it but activated it.

heal_network:
  description: Start a Z-Wave network heal. This might take a while and will slow down the Z-Wave network greatly while it is being processed. Refer to OZW.log for details.

remove_node:
  description: Remove a node from the Z-Wave network. Refer to OZW.log for details.

remove_failed_node:
  descsription: This command will remove a failed node from the network. The node should be on the controllers failed nodes list, otherwise this command will fail. Refer to OZW.log for details.
  fields:
    node_id:
      description: Node id of the device to remove (integer).

replace_failed_node:
  descsription: Replace a failed node with another. If the node is not in the controller's failed nodes list, or the node responds, this command will fail. Refer to OZW.log for details.
  fields:
    node_id:
      description: Node id of the device to replace (integer).

set_config_parameter:
  description: Set a config parameter to a node on the Z-Wave network.
  fields:
    node_id:
      description: Node id of the device to set config parameter to (integer).
    parameter:
      description: Parameter number to set (integer).
    value:
      description: Value to set for parameter. (String value for list and bool parameters, integer for others).
    size:
      description: (Optional) Set the size of the parameter value. Only needed if no parameters are available.

print_config_parameter:
  description: Prints a Z-Wave node config parameter value to log.
  fields:
    node_id:
      description: Node id of the device to print the parameter from (integer).
    parameter:
      description: Parameter number to print (integer).

print_node:
  description: Print all information about z-wave node.
  fields:
    node_id:
      description: Node id of the device to print.

refresh_entity:
  description: Refresh zwave entity.
  fields:
    entity_id:
      description: Name of the entity to refresh.
      example: 'light.leviton_vrmx11lz_multilevel_scene_switch_level_40'

refresh_node:
  description: Refresh zwave node.
  fields:
    node_id:
      description: ID of the node to refresh.
      example: 10

set_wakeup:
  description: Sets wake-up interval of a node.
  fields:
    node_id:
      description: Node id of the device to set the wake-up interval for. (integer)
    value:
      description: Value of the interval to set. (integer)

start_network:
  description: Start the Z-Wave network. This might take a while, depending on how big your Z-Wave network is.

stop_network:
  description: Stop the Z-Wave network, all updates into HASS will stop.

soft_reset:
  description: This will reset the controller without removing its data. Use carefully because not all controllers support this. Refer to controllers manual.

test_network:
  description: This will send test to nodes in the Z-Wave network. This will greatly slow down the Z-Wave network while it is being processed. Refer to OZW.log for details.

rename_node:
  description: Set the name(s) of a node.
  fields:
    node_id:
      description: ID of the node to rename.
      example: 10
    name:
      description: New Name
      example: 'kitchen'

rename_value:
  description: Set the name of a node value. Value IDs can be queried from /api/zwave/values/{node_id}
  fields:
    node_id:
      description: ID of the node to rename.
      example: 10
    value_id:
      description: ID of the value to rename.
      example: 72037594255792737
    name:
      description: New Name
      example: 'Luminosity'

reset_node_meters:
  description: Resets the meter counters of a node.
  fields:
    node_id:
      description: Node id of the device to reset meters for. (integer)
    instance:
      description: (Optional) Instance of association. Defaults to instance 1.
