set_profile:
  name: Set profile
  description: Set the ventilation profile.
  fields:
    profile:
      name: Profile
      description: "Set profile."
      required: true
      selector:
        select:
          options:
            - 'Away'
            - 'Boost'
            - 'Fireplace'
            - 'Home'

set_profile_fan_speed_home:
  name: Set profile fan speed hom
  description: Set the fan speed of the Home profile.
  fields:
    fan_speed:
      name: Fan speed
      description: Fan speed.
      required: true
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: '%'

set_profile_fan_speed_away:
  name: Set profile fan speed away
  description: Set the fan speed of the Away profile.
  fields:
    fan_speed:
      name: Fan speed
      description: Fan speed.
      required: true
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: '%'

set_profile_fan_speed_boost:
  name: Set profile fan speed boost
  description: Set the fan speed of the Boost profile.
  fields:
    fan_speed:
      name: Fan speed
      description: Fan speed.
      required: true
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: '%'
