heat_set:
  name: Heat set
  description: Set heating/cooling level for eight sleep.
  fields:
    duration:
      name: Duration
      description: Duration to heat/cool at the target level in seconds.
      required: true
      selector:
        number:
          min: 0
          max: 28800
          unit_of_measurement: seconds
    entity_id:
      name: Entity
      description: Entity id of the bed state to adjust.
      required: true
      selector:
        entity:
          integration: eight_sleep
          domain: sensor
    target:
      name: Target
      description: Target cooling/heating level from -100 to 100.
      required: true
      selector:
        number:
          min: -100
          max: 100
          unit_of_measurement: 'Â°'
