# Describes the format for available MQTT services

publish:
  fields:
    topic:
      required: true
      example: /homeassistant/hello
      selector:
        text:
    payload:
      required: true
      example: "The temperature is {{ states('sensor.temperature') }}"
      selector:
        template:
    qos:
      advanced: true
      default: 0
      selector:
        select:
          options:
            - "0"
            - "1"
            - "2"
    retain:
      default: false
      selector:
        boolean:

dump:
  fields:
    topic:
      example: "OpenZWave/#"
      selector:
        text:
    duration:
      default: 5
      selector:
        number:
          min: 1
          max: 300
          unit_of_measurement: "seconds"

reload:
