# Describes the format for available component services

activate_eco_mode_with_duration:
  description: Activate eco mode with period.
  fields:
    duration:
      description: The duration of eco mode in minutes.
      example: 60
    accesspoint_id:
      description: The ID of the Homematic IP Access Point (optional)
      example: 3014xxxxxxxxxxxxxxxxxxxx

activate_eco_mode_with_period:
  description: Activate eco mode with period.
  fields:
    endtime:
      description: The time when the eco mode should automatically be disabled.
      example: 2019-02-17 14:00
    accesspoint_id:
      description: The ID of the Homematic IP Access Point (optional)
      example: 3014xxxxxxxxxxxxxxxxxxxx

activate_vacation:
  description: Activates the vacation mode until the given time.
  fields:
    endtime:
      description: The time when the vacation mode should automatically be disabled.
      example: 2019-09-17 14:00
    temperature:
      description: the set temperature during the vacation mode.
      example: 18.5
    accesspoint_id:
      description: The ID of the Homematic IP Access Point (optional)
      example: 3014xxxxxxxxxxxxxxxxxxxx

deactivate_eco_mode:
  description: Deactivates the eco mode immediately.
  fields:
    accesspoint_id:
      description: The ID of the Homematic IP Access Point (optional)
      example: 3014xxxxxxxxxxxxxxxxxxxx

deactivate_vacation:
  description: Deactivates the vacation mode immediately.
  fields:
    accesspoint_id:
      description: The ID of the Homematic IP Access Point (optional)
      example: 3014xxxxxxxxxxxxxxxxxxxx

set_active_climate_profile:
  description: Set the active climate profile index.
  fields:
    entity_id:
      description: The ID of the climte entity. Use 'all' keyword to switch the profile for all entities.
      example: climate.livingroom
    climate_profile_index:
      description: The index of the climate profile (1 based)
      example: 1

dump_hap_config:
  description: Dump the configuration of the Homematic IP Access Point(s).
  fields:
    config_output_path:
      description: (Default is 'Your home-assistant config directory') Path where to store the config.
      example: "/config"
    config_output_file_prefix:
      description: (Default is 'hmip-config') Name of the config file. The SGTIN of the AP will always be appended.
      example: "hmip-config"
    anonymize:
      description: (Default is True) Should the Configuration be anonymized?
      example: true

reset_energy_counter:
  description: Reset the energy counter of a measuring entity.
  fields:
    entity_id:
      description: The ID of the measuring entity. Use 'all' keyword to reset all energy counters.
      example: switch.livingroom
