update_setting:
  name: Update a Vizio media player setting
  description: Update the value of a setting on a Vizio media player device.
  target:
    entity:
      integration: vizio
      domain: media_player
  fields:
    setting_type:
      name: Setting type
      description: The type of setting to be changed. Available types are listed in the 'setting_types' property.
      required: true
      example: "audio"
      selector:
        text:
    setting_name:
      name: Setting name
      description: The name of the setting to be changed. Available settings for a given setting_type are listed in the '<setting_type>_settings' property.
      required: true
      example: "eq"
      selector:
        text:
    new_value:
      name: New value
      description: The new value for the setting.
      required: true
      example: "Music"
      selector:
        text:
