open_cover:
  description: Open all or specified cover

  fields:
    entity_id:
      description: Name(s) of cover(s) to open
      example: 'cover.living_room'

close_cover:
  description: Close all or specified cover

  fields:
    entity_id:
      description: Name(s) of cover(s) to close
      example: 'cover.living_room'

set_cover_position:
  description: Move to specific position all or specified cover

  fields:
    entity_id:
      description: Name(s) of cover(s) to set cover position
      example: 'cover.living_room'

    position:
      description: Position of the cover (0 to 100)
      example: 30

stop_cover:
  description: Stop all or specified cover

  fields:
    entity_id:
      description: Name(s) of cover(s) to stop
      example: 'cover.living_room'

open_cover_tilt:
  description: Open all or specified cover tilt

  fields:
    entity_id:
      description: Name(s) of cover(s) tilt to open
      example: 'cover.living_room'

close_cover_tilt:
  description: Close all or specified cover tilt

  fields:
    entity_id:
      description: Name(s) of cover(s) to close tilt
      example: 'cover.living_room'

set_cover_tilt_position:
  description: Move to specific position all or specified cover tilt

  fields:
    entity_id:
      description: Name(s) of cover(s) to set cover tilt position
      example: 'cover.living_room'

    position:
      description: Position of the cover (0 to 100)
      example: 30

stop_cover_tilt:
  description: Stop all or specified cover

  fields:
    entity_id:
      description: Name(s) of cover(s) to stop
      example: 'cover.living_room'
