# Describes the format for available alarm control panel services

alarm_disarm:
  description: Send the alarm the command for disarm.
  fields:
    entity_id:
      description: Name of alarm control panel to disarm.
      example: 'alarm_control_panel.downstairs'
    code:
      description: An optional code to disarm the alarm control panel with.
      example: 1234

alarm_arm_custom_bypass:
  description: Send arm custom bypass command.
  fields:
    entity_id:
      description: Name of alarm control panel to arm custom bypass.
      example: 'alarm_control_panel.downstairs'
    code:
      description: An optional code to arm custom bypass the alarm control panel with.
      example: 1234

alarm_arm_home:
  description: Send the alarm the command for arm home.
  fields:
    entity_id:
      description: Name of alarm control panel to arm home.
      example: 'alarm_control_panel.downstairs'
    code:
      description: An optional code to arm home the alarm control panel with.
      example: 1234

alarm_arm_away:
  description: Send the alarm the command for arm away.
  fields:
    entity_id:
      description: Name of alarm control panel to arm away.
      example: 'alarm_control_panel.downstairs'
    code:
      description: An optional code to arm away the alarm control panel with.
      example: 1234

alarm_arm_night:
  description: Send the alarm the command for arm night.
  fields:
    entity_id:
      description: Name of alarm control panel to arm night.
      example: 'alarm_control_panel.downstairs'
    code:
      description: An optional code to arm night the alarm control panel with.
      example: 1234

alarm_trigger:
  description: Send the alarm the command for trigger.
  fields:
    entity_id:
      description: Name of alarm control panel to trigger.
      example: 'alarm_control_panel.downstairs'
    code:
      description: An optional code to trigger the alarm control panel with.
      example: 1234

alarmdecoder_alarm_toggle_chime:
  description: Send the alarm the toggle chime command.
  fields:
    entity_id:
      description: Name of the alarm control panel to trigger.
      example: 'alarm_control_panel.downstairs'
    code:
      description: A required code to toggle the alarm control panel chime with.
      example: 1234

ifttt_push_alarm_state:
  description: Update the alarm state to the specified value.
  fields:
    entity_id:
      description: Name of the alarm control panel which state has to be updated.
      example: 'alarm_control_panel.downstairs'
    state:
      description: The state to which the alarm control panel has to be set.
      example: 'armed_night'
