set_guest_wifi_password:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: fritz
          entity:
            device_class: connectivity
    password:
      required: false
      selector:
        text:
    length:
      required: false
      selector:
        number:
          min: 8
          max: 63
dial:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: fritz
          entity:
            device_class: connectivity
    number:
      required: true
      selector:
        text:
    max_ring_seconds:
      default: 15
      required: true
      selector:
        number:
          min: 1
          max: 300
          step: 1
          unit_of_measurement: seconds
