create_event:
  name: Create event
  description: Add a new calendar event.
  target:
    entity:
      domain: calendar
  fields:
    summary:
      name: Summary
      description: Defines the short summary or subject for the event
      required: true
      example: "Department Party"
      selector:
        text:
    description:
      name: Description
      description: A more complete description of the event than that provided by the summary.
      example: "Meeting to provide technical review for 'Phoenix' design."
      selector:
        text:
    start_date_time:
      name: Start time
      description: The date and time the event should start.
      example: "2022-03-22 20:00:00"
      selector:
        datetime:
    end_date_time:
      name: End time
      description: The date and time the event should end.
      example: "2022-03-22 22:00:00"
      selector:
        datetime:
    start_date:
      name: Start date
      description: The date the all-day event should start.
      example: "2022-03-22"
      selector:
        date:
    end_date:
      name: End date
      description: The date the all-day event should end (exclusive).
      example: "2022-03-23"
      selector:
        date:
    in:
      name: In
      description: Days or weeks that you want to create the event in.
      example: '{"days": 2} or {"weeks": 2}'
