reconnect_client:
  fields:
    config_entry_id:
      selector:
        config_entry:
          integration: tplink_omada
    mac:
      required: true
      example: "01-23-45-67-89-AB"
      selector:
        text:
