reconnect_client:
  fields:
    config_entry_id:
      selector:
        config_entry:
          integration: tplink_omada
    mac:
      required: true
      example: "01-23-45-67-89-AB"
      selector:
        text:

cleanup_client_trackers:
  fields:
    entity_id:
      selector:
        entity:
          domain: device_tracker
          integration: tplink_omada
          multiple: true
