# Describes the format for available camera services

enable_motion_detection:
  description: Enable the motion detection in a camera.
  fields:
    entity_id:
      description: Name(s) of entities to enable motion detection.
      example: 'camera.living_room_camera'

disable_motion_detection:
  description: Disable the motion detection in a camera.
  fields:
    entity_id:
      description: Name(s) of entities to disable motion detection.
      example: 'camera.living_room_camera'

snapshot:
  description: Take a snapshot from a camera.
  fields:
    entity_id:
      description: Name(s) of entities to create snapshots from.
      example: 'camera.living_room_camera'
    filename:
      description: Template of a Filename. Variable is entity_id.
      example: '/tmp/snapshot_{{ entity_id }}'

local_file_update_file_path:
  description: Update the file_path for a local_file camera.
  fields:
    entity_id:
      description: Name(s) of entities to update.
      example: 'camera.local_file'
    file_path:
      description: Path to the new image file.
      example: '/images/newimage.jpg'

onvif_ptz:
  description: Pan/Tilt/Zoom service for ONVIF camera.
  fields:
    entity_id:
      description: Name(s) of entities to pan, tilt or zoom.
      example: 'camera.living_room_camera'
    pan:
      description: "Direction of pan. Allowed values: LEFT, RIGHT."
      example: 'LEFT'
    tilt:
      description: "Direction of tilt. Allowed values: DOWN, UP."
      example: 'DOWN'
    zoom:
      description: "Zoom. Allowed values: ZOOM_IN, ZOOM_OUT"
      example: "ZOOM_IN"
