boost_heating:
  description: "Set the boost mode ON defining the period of time and the desired target temperature or temperature increase delta for the boost.  Setting the temperature delta overrides any target temperature."
  fields:
    entity_id:
      {
        description: "Enter the entity_id for the room required to set the boost mode.",
        example: "climate.wiser_lounge",
      }
    time_period:
      {
        description: "Set the time period for the boost in minutes.",
        example: "60",
      }
    temperature:
      {
        description: "Set the target temperature for the boost period.",
        example: "20.5",
      }
    temperature_delta:
      {
        description: "Set the temperature increase for the boost period.",
        example: "2",
      }
get_schedule:
  description: "Read the schedule from a roomId and write to an output file in yaml"
  fields:
    entity_id:
      {
        description: "Enter the entity_id for the room to read the schedule.",
        example: "climate.wiser_lounge",
      }
    filename:
      {
        description: "The filename to write out the yaml. See README.MD if running within a docker container.",
        example: "schedule1.yaml",
      }
set_schedule:
  description: "Read in the yaml schedule file and set the schedule in a room"
  fields:
    entity_id:
      {
        description: "Enter the entity_id for the room to set the schedule.",
        example: "climate.wiser_lounge",
      }
    filename:
      {
        description: "The filename to read the yaml schedule from.",
        example: "schedules/schedule1.yaml",
      }
copy_schedule:
  description: "Copy the schedule in a room to another room"
  fields:
    entity_id:
      {
        description: "Enter the entity_id for the room to copy the schedule from.",
        example: "climate.wiser_lounge",
      }
    to_entity_id:
      {
        description: "Enter the entity_id for the room to copy the schedule to.",
        example: "climate.wiser_kitchen",
      }
set_smartplug_mode:
  description: "Sets the mode of a smart plug"
  fields:
    entity_id:
      {
        description: "Enter the entity_id for the smartplug.",
        example: "switch.smartplug",
      }
    plug_mode: { description: "Enter the mode, can
          be auto or manual.", example: "auto" }
set_hotwater_mode:
  description: "Sets the hot water mode"
  fields:
    hotwater_mode:
      {
        description: "Enter the mode can be on , off or auto.",
        example: "auto",
      }
