override_schedule:
  target:
    entity:
      integration: "husqvarna_automower"
      domain: "lawn_mower"
  fields:
    duration:
      required: true
      example: "{'days': 1, 'hours': 12, 'minutes': 30}"
      selector:
        duration:
          enable_day: true
    override_mode:
      required: true
      example: "mow"
      selector:
        select:
          translation_key: override_modes
          options:
            - "mow"
            - "park"
    external_reason:
      required: false
      example: "200000"
      selector:
        number:
          min: 200000
          max: 299999

override_schedule_work_area:
  target:
    entity:
      integration: "husqvarna_automower"
      domain: "lawn_mower"
  fields:
    duration:
      required: true
      example: "{'days': 1, 'hours': 12, 'minutes': 30}"
      selector:
        duration:
          enable_day: true
    work_area_id:
      required: true
      example: "123"
      selector:
        text:
          type: number
