water_heater_boost:
  target:
    entity:
      domain: water_heater
  fields:
    duration:
      selector:
        number:
          min: 60
          max: 14400
          step: 60
          mode: box
      default: 3600
      required: true
    emergencyBoost:
      selector:
        boolean:
      default: false
    temporarySetpoint:
      selector:
        number:
          min: 30
          max: 65
          step: 1
          mode: slider
      default: 65

water_heater_cancel_boost:
  target:
    entity:
      domain: water_heater
