# Service descriptions for Matter integration

get_areas:
  target:
    entity:
      domain: vacuum

select_areas:
  target:
    entity:
      domain: vacuum
  fields:
    areas:
      required: true
      example: [1, 3]

clean_areas:
  target:
    entity:
      domain: vacuum
  fields:
    areas:
      required: true
      example: [1, 3]
