water_heater_boost:
  target:
    entity:
      domain: water_heater
      integration: matter
  fields:
    duration:
      selector:
        number:
          min: 60
          max: 14400
          step: 60
          mode: box
      default: 3600
      required: true
    emergency_boost:
      selector:
        boolean:
      default: false
    temporary_setpoint:
      selector:
        number:
          min: 30
          max: 65
          step: 1
          mode: slider
      default: 65

set_lock_usercode:
  target:
    entity:
      domain: lock
      integration: matter
  fields:
    code_slot:
      required: true
      example: 1
      selector:
        number:
          min: 1
          max: 255 # Common max user codes
          mode: box
    usercode:
      required: true
      example: "1234"
      selector:
        text:

clear_lock_usercode:
  target:
    entity:
      domain: lock
      integration: matter
  fields:
    code_slot:
      required: true
      example: 1
      selector:
        number:
          min: 1
          max: 255
          mode: box
