# Service descriptions for Matter integration

get_areas:
  target:
    entity:
      integration: matter
      domain: vacuum

clean_areas:
  target:
    entity:
      integration: matter
      domain: vacuum
  fields:
    areas:
      required: true
      example:
        - 1
        - 3
