water_heater_boost:
  target:
    entity:
      domain: water_heater
    integration: matter
  fields:
    duration:
      selector:
        number:
          min: 60
          max: 14400
          step: 60
          mode: box
      required: true
    emergencyBoost:
      selector:
        boolean:
    temporarySetpoint:
      selector:
        number:
          min: 30
          max: 75
          step: 1
          mode: box

water_heater_cancel_boost:
  target:
    entity:
      domain: water_heater
    integration: matter
