# Describes the format for available light services

turn_on:
  target:
    entity:
      domain: light
  fields:
    transition:
      filter:
        supported_features:
          - light.LightEntityFeature.TRANSITION
      selector:
        number:
          min: 0
          max: 300
          unit_of_measurement: seconds
    rgb_color:
      filter:
        attribute:
          supported_color_modes:
            - light.ColorMode.HS
            - light.ColorMode.XY
            - light.ColorMode.RGB
            - light.ColorMode.RGBW
            - light.ColorMode.RGBWW
      selector:
        color_rgb:
    rgbw_color:
      filter:
        attribute:
          supported_color_modes:
            - light.ColorMode.HS
            - light.ColorMode.XY
            - light.ColorMode.RGB
            - light.ColorMode.RGBW
            - light.ColorMode.RGBWW
      advanced: true
      example: "[255, 100, 100, 50]"
      selector:
        object:
    rgbww_color:
      filter:
        attribute:
          supported_color_modes:
            - light.ColorMode.HS
            - light.ColorMode.XY
            - light.ColorMode.RGB
            - light.ColorMode.RGBW
            - light.ColorMode.RGBWW
      advanced: true
      example: "[255, 100, 100, 50, 70]"
      selector:
        object:
    color_name:
      filter:
        attribute:
          supported_color_modes:
            - light.ColorMode.HS
            - light.ColorMode.XY
            - light.ColorMode.RGB
            - light.ColorMode.RGBW
            - light.ColorMode.RGBWW
      advanced: true
      selector:
        select:
          translation_key: color_name
          options:
            - "homeassistant"
            - "aliceblue"
            - "antiquewhite"
            - "aqua"
            - "aquamarine"
            - "azure"
            - "beige"
            - "bisque"
            # Black is omitted from this list as nonsensical for lights
            - "blanchedalmond"
            - "blue"
            - "blueviolet"
            - "brown"
            - "burlywood"
            - "cadetblue"
            - "chartreuse"
            - "chocolate"
            - "coral"
            - "cornflowerblue"
            - "cornsilk"
            - "crimson"
            - "cyan"
            - "darkblue"
            - "darkcyan"
            - "darkgoldenrod"
            - "darkgray"
            - "darkgreen"
            - "darkgrey"
            - "darkkhaki"
            - "darkmagenta"
            - "darkolivegreen"
            - "darkorange"
            - "darkorchid"
            - "darkred"
            - "darksalmon"
            - "darkseagreen"
            - "darkslateblue"
            - "darkslategray"
            - "darkslategrey"
            - "darkturquoise"
            - "darkviolet"
            - "deeppink"
            - "deepskyblue"
            - "dimgray"
            - "dimgrey"
            - "dodgerblue"
            - "firebrick"
            - "floralwhite"
            - "forestgreen"
            - "fuchsia"
            - "gainsboro"
            - "ghostwhite"
            - "gold"
            - "goldenrod"
            - "gray"
            - "green"
            - "greenyellow"
            - "grey"
            - "honeydew"
            - "hotpink"
            - "indianred"
            - "indigo"
            - "ivory"
            - "khaki"
            - "lavender"
            - "lavenderblush"
            - "lawngreen"
            - "lemonchiffon"
            - "lightblue"
            - "lightcoral"
            - "lightcyan"
            - "lightgoldenrodyellow"
            - "lightgray"
            - "lightgreen"
            - "lightgrey"
            - "lightpink"
            - "lightsalmon"
            - "lightseagreen"
            - "lightskyblue"
            - "lightslategray"
            - "lightslategrey"
            - "lightsteelblue"
            - "lightyellow"
            - "lime"
            - "limegreen"
            - "linen"
            - "magenta"
            - "maroon"
            - "mediumaquamarine"
            - "mediumblue"
            - "mediumorchid"
            - "mediumpurple"
            - "mediumseagreen"
            - "mediumslateblue"
            - "mediumspringgreen"
            - "mediumturquoise"
            - "mediumvioletred"
            - "midnightblue"
            - "mintcream"
            - "mistyrose"
            - "moccasin"
            - "navajowhite"
            - "navy"
            - "navyblue"
            - "oldlace"
            - "olive"
            - "olivedrab"
            - "orange"
            - "orangered"
            - "orchid"
            - "palegoldenrod"
            - "palegreen"
            - "paleturquoise"
            - "palevioletred"
            - "papayawhip"
            - "peachpuff"
            - "peru"
            - "pink"
            - "plum"
            - "powderblue"
            - "purple"
            - "red"
            - "rosybrown"
            - "royalblue"
            - "saddlebrown"
            - "salmon"
            - "sandybrown"
            - "seagreen"
            - "seashell"
            - "sienna"
            - "silver"
            - "skyblue"
            - "slateblue"
            - "slategray"
            - "slategrey"
            - "snow"
            - "springgreen"
            - "steelblue"
            - "tan"
            - "teal"
            - "thistle"
            - "tomato"
            - "turquoise"
            - "violet"
            - "wheat"
            - "white"
            - "whitesmoke"
            - "yellow"
            - "yellowgreen"
    hs_color:
      filter:
        attribute:
          supported_color_modes:
            - light.ColorMode.HS
            - light.ColorMode.XY
            - light.ColorMode.RGB
            - light.ColorMode.RGBW
            - light.ColorMode.RGBWW
      advanced: true
      example: "[300, 70]"
      selector:
        object:
    xy_color:
      filter:
        attribute:
          supported_color_modes:
            - light.ColorMode.HS
            - light.ColorMode.XY
            - light.ColorMode.RGB
            - light.ColorMode.RGBW
            - light.ColorMode.RGBWW
      advanced: true
      example: "[0.52, 0.43]"
      selector:
        object:
    color_temp:
      filter:
        attribute:
          supported_color_modes:
            - light.ColorMode.COLOR_TEMP
            - light.ColorMode.HS
            - light.ColorMode.XY
            - light.ColorMode.RGB
            - light.ColorMode.RGBW
            - light.ColorMode.RGBWW
      selector:
        color_temp:
          unit: "mired"
          min: 153
          max: 500
    kelvin:
      filter:
        attribute:
          supported_color_modes:
            - light.ColorMode.COLOR_TEMP
            - light.ColorMode.HS
            - light.ColorMode.XY
            - light.ColorMode.RGB
            - light.ColorMode.RGBW
            - light.ColorMode.RGBWW
      advanced: true
      selector:
        color_temp:
          unit: "kelvin"
          min: 2000
          max: 6500
    brightness:
      filter:
        attribute:
          supported_color_modes:
            - light.ColorMode.BRIGHTNESS
            - light.ColorMode.COLOR_TEMP
            - light.ColorMode.HS
            - light.ColorMode.XY
            - light.ColorMode.RGB
            - light.ColorMode.RGBW
            - light.ColorMode.RGBWW
      advanced: true
      selector:
        number:
          min: 0
          max: 255
    brightness_pct:
      filter:
        attribute:
          supported_color_modes:
            - light.ColorMode.BRIGHTNESS
            - light.ColorMode.COLOR_TEMP
            - light.ColorMode.HS
            - light.ColorMode.XY
            - light.ColorMode.RGB
            - light.ColorMode.RGBW
            - light.ColorMode.RGBWW
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    brightness_step:
      filter:
        attribute:
          supported_color_modes:
            - light.ColorMode.BRIGHTNESS
            - light.ColorMode.COLOR_TEMP
            - light.ColorMode.HS
            - light.ColorMode.XY
            - light.ColorMode.RGB
            - light.ColorMode.RGBW
            - light.ColorMode.RGBWW
      advanced: true
      selector:
        number:
          min: -225
          max: 255
    brightness_step_pct:
      filter:
        attribute:
          supported_color_modes:
            - light.ColorMode.BRIGHTNESS
            - light.ColorMode.COLOR_TEMP
            - light.ColorMode.HS
            - light.ColorMode.XY
            - light.ColorMode.RGB
            - light.ColorMode.RGBW
            - light.ColorMode.RGBWW
      selector:
        number:
          min: -100
          max: 100
          unit_of_measurement: "%"
    white:
      filter:
        attribute:
          supported_color_modes:
            - light.ColorMode.WHITE
      advanced: true
      selector:
        constant:
          value: true
          label: Enabled
    profile:
      advanced: true
      example: relax
      selector:
        text:
    flash:
      filter:
        supported_features:
          - light.LightEntityFeature.FLASH
      advanced: true
      selector:
        select:
          options:
            - label: "Long"
              value: "long"
            - label: "Short"
              value: "short"
    effect:
      filter:
        supported_features:
          - light.LightEntityFeature.EFFECT
      selector:
        text:

turn_off:
  target:
    entity:
      domain: light
  fields:
    transition:
      filter:
        supported_features:
          - light.LightEntityFeature.TRANSITION
      selector:
        number:
          min: 0
          max: 300
          unit_of_measurement: seconds
    flash:
      filter:
        supported_features:
          - light.LightEntityFeature.FLASH
      advanced: true
      selector:
        select:
          options:
            - label: "Long"
              value: "long"
            - label: "Short"
              value: "short"

toggle:
  target:
    entity:
      domain: light
  fields:
    transition:
      filter:
        supported_features:
          - light.LightEntityFeature.TRANSITION
      selector:
        number:
          min: 0
          max: 300
          unit_of_measurement: seconds
    rgb_color:
      filter:
        attribute:
          supported_color_modes:
            - light.ColorMode.HS
            - light.ColorMode.XY
            - light.ColorMode.RGB
            - light.ColorMode.RGBW
            - light.ColorMode.RGBWW
      advanced: true
      example: "[255, 100, 100]"
      selector:
        color_rgb:
    color_name:
      filter:
        attribute:
          supported_color_modes:
            - light.ColorMode.HS
            - light.ColorMode.XY
            - light.ColorMode.RGB
            - light.ColorMode.RGBW
            - light.ColorMode.RGBWW
      advanced: true
      selector:
        select:
          translation_key: color_name
          options:
            - "homeassistant"
            - "aliceblue"
            - "antiquewhite"
            - "aqua"
            - "aquamarine"
            - "azure"
            - "beige"
            - "bisque"
            # Black is omitted from this list as nonsensical for lights
            - "blanchedalmond"
            - "blue"
            - "blueviolet"
            - "brown"
            - "burlywood"
            - "cadetblue"
            - "chartreuse"
            - "chocolate"
            - "coral"
            - "cornflowerblue"
            - "cornsilk"
            - "crimson"
            - "cyan"
            - "darkblue"
            - "darkcyan"
            - "darkgoldenrod"
            - "darkgray"
            - "darkgreen"
            - "darkgrey"
            - "darkkhaki"
            - "darkmagenta"
            - "darkolivegreen"
            - "darkorange"
            - "darkorchid"
            - "darkred"
            - "darksalmon"
            - "darkseagreen"
            - "darkslateblue"
            - "darkslategray"
            - "darkslategrey"
            - "darkturquoise"
            - "darkviolet"
            - "deeppink"
            - "deepskyblue"
            - "dimgray"
            - "dimgrey"
            - "dodgerblue"
            - "firebrick"
            - "floralwhite"
            - "forestgreen"
            - "fuchsia"
            - "gainsboro"
            - "ghostwhite"
            - "gold"
            - "goldenrod"
            - "gray"
            - "green"
            - "greenyellow"
            - "grey"
            - "honeydew"
            - "hotpink"
            - "indianred"
            - "indigo"
            - "ivory"
            - "khaki"
            - "lavender"
            - "lavenderblush"
            - "lawngreen"
            - "lemonchiffon"
            - "lightblue"
            - "lightcoral"
            - "lightcyan"
            - "lightgoldenrodyellow"
            - "lightgray"
            - "lightgreen"
            - "lightgrey"
            - "lightpink"
            - "lightsalmon"
            - "lightseagreen"
            - "lightskyblue"
            - "lightslategray"
            - "lightslategrey"
            - "lightsteelblue"
            - "lightyellow"
            - "lime"
            - "limegreen"
            - "linen"
            - "magenta"
            - "maroon"
            - "mediumaquamarine"
            - "mediumblue"
            - "mediumorchid"
            - "mediumpurple"
            - "mediumseagreen"
            - "mediumslateblue"
            - "mediumspringgreen"
            - "mediumturquoise"
            - "mediumvioletred"
            - "midnightblue"
            - "mintcream"
            - "mistyrose"
            - "moccasin"
            - "navajowhite"
            - "navy"
            - "navyblue"
            - "oldlace"
            - "olive"
            - "olivedrab"
            - "orange"
            - "orangered"
            - "orchid"
            - "palegoldenrod"
            - "palegreen"
            - "paleturquoise"
            - "palevioletred"
            - "papayawhip"
            - "peachpuff"
            - "peru"
            - "pink"
            - "plum"
            - "powderblue"
            - "purple"
            - "red"
            - "rosybrown"
            - "royalblue"
            - "saddlebrown"
            - "salmon"
            - "sandybrown"
            - "seagreen"
            - "seashell"
            - "sienna"
            - "silver"
            - "skyblue"
            - "slateblue"
            - "slategray"
            - "slategrey"
            - "snow"
            - "springgreen"
            - "steelblue"
            - "tan"
            - "teal"
            - "thistle"
            - "tomato"
            - "turquoise"
            - "violet"
            - "wheat"
            - "white"
            - "whitesmoke"
            - "yellow"
            - "yellowgreen"
    hs_color:
      filter:
        attribute:
          supported_color_modes:
            - light.ColorMode.HS
            - light.ColorMode.XY
            - light.ColorMode.RGB
            - light.ColorMode.RGBW
            - light.ColorMode.RGBWW
      advanced: true
      example: "[300, 70]"
      selector:
        object:
    xy_color:
      filter:
        attribute:
          supported_color_modes:
            - light.ColorMode.HS
            - light.ColorMode.XY
            - light.ColorMode.RGB
            - light.ColorMode.RGBW
            - light.ColorMode.RGBWW
      advanced: true
      example: "[0.52, 0.43]"
      selector:
        object:
    color_temp:
      filter:
        attribute:
          supported_color_modes:
            - light.ColorMode.COLOR_TEMP
            - light.ColorMode.HS
            - light.ColorMode.XY
            - light.ColorMode.RGB
            - light.ColorMode.RGBW
            - light.ColorMode.RGBWW
      advanced: true
      selector:
        color_temp:
    kelvin:
      filter:
        attribute:
          supported_color_modes:
            - light.ColorMode.COLOR_TEMP
            - light.ColorMode.HS
            - light.ColorMode.XY
            - light.ColorMode.RGB
            - light.ColorMode.RGBW
            - light.ColorMode.RGBWW
      advanced: true
      selector:
        color_temp:
          unit: "kelvin"
          min: 2000
          max: 6500
    brightness:
      filter:
        attribute:
          supported_color_modes:
            - light.ColorMode.BRIGHTNESS
            - light.ColorMode.COLOR_TEMP
            - light.ColorMode.HS
            - light.ColorMode.XY
            - light.ColorMode.RGB
            - light.ColorMode.RGBW
            - light.ColorMode.RGBWW
      advanced: true
      selector:
        number:
          min: 0
          max: 255
    brightness_pct:
      filter:
        attribute:
          supported_color_modes:
            - light.ColorMode.BRIGHTNESS
            - light.ColorMode.COLOR_TEMP
            - light.ColorMode.HS
            - light.ColorMode.XY
            - light.ColorMode.RGB
            - light.ColorMode.RGBW
            - light.ColorMode.RGBWW
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    white:
      filter:
        attribute:
          supported_color_modes:
            - light.ColorMode.WHITE
      advanced: true
      selector:
        constant:
          value: true
          label: Enabled
    profile:
      advanced: true
      example: relax
      selector:
        text:
    flash:
      filter:
        supported_features:
          - light.LightEntityFeature.FLASH
      advanced: true
      selector:
        select:
          options:
            - label: "Long"
              value: "long"
            - label: "Short"
              value: "short"
    effect:
      filter:
        supported_features:
          - light.LightEntityFeature.EFFECT
      selector:
        text:
