take_sample:
  name: Sample Data
  description: Generates Sample Data from a given UniFi Protect instance. Useful for debugging or reporting issues.
  fields:
    device_id:
      name: UniFi Protect NVR
      description: Main NVR for the UniFi Protect instance you would like to target.
      required: true
      selector:
        device:
          integration: unifiprotect
    duration:
      name: Websocket Capture Time
      description: How long to capture Websocket messages for.
      default: 30
      required: true
      selector:
        number:
          min: 0
          max: 600
          step: 10
          unit_of_measurement: seconds
    anonymize:
      name: Anonymize Data
      description: Data is anonymized by default to make safe for distribution.
      default: true
      required: true
      selector:
        boolean:
profile_ws_messages:
  name: Profile WS Messages
  description: Profiles UniFi Protect Web Socket messages and prints out summary afterwards. Useful for benchmarking or reporting issues.
  fields:
    device_id:
      name: UniFi Protect NVR
      description: Main NVR for the UniFi Protect instance you would like to target.
      required: true
      selector:
        device:
          integration: unifiprotect
    duration:
      name: Profile Time
      description: How long to profile
      default: 60
      required: true
      selector:
        number:
          min: 10
          max: 600
          step: 10
          unit_of_measurement: seconds
add_doorbell_text:
  name: Add Custom Doorbell Text
  description: Adds a new custom message for Doorbells. You must restart Home Assistant afterwards for text options updates to appear on doorbells.
  fields:
    device_id:
      name: UniFi Protect NVR
      description: Main NVR for the UniFi Protect instance you would like to target.
      required: true
      selector:
        device:
          integration: unifiprotect
    message:
      name: Custom Message
      description: The custom message to add. Max length of 30 characters.
      example: Come In
      required: true
      selector:
        text:
remove_doorbell_text:
  name: Remove Custom Doorbell Text
  description: Removes an existing message for Doorbells. You must restart Home Assistant afterwards for text options updates to appear on doorbells.
  fields:
    device_id:
      name: UniFi Protect NVR
      description: Main NVR for the UniFi Protect instance you would like to target.
      required: true
      selector:
        device:
          integration: unifiprotect
    message:
      name: Custom Message
      description: The custom message to remove. Max length of 30 characters.
      example: Go Away!
      required: true
      selector:
        text:
set_default_doorbell_text:
  name: Set Default Doorbell Text
  description: Sets the default doorbell message. You must restart Home Assistant afterwards for text options updates to appear on doorbells.
  fields:
    device_id:
      name: UniFi Protect NVR
      description: Main NVR for the UniFi Protect instance you would like to target.
      required: true
      selector:
        device:
          integration: unifiprotect
    message:
      name: Default Message
      description: The default message. Max length of 30 characters.
      example: Welcome!
      required: true
      selector:
        text:
set_doorbell_message:
  name: Set Doorbell message
  description: >
    Use to dynamically set the message on a Doorbell LCD screen. Should only be used to set dynamic messages
    (i.e. setting the current outdoor temperature on your Doorbell). Static messages should still using the Select entity and the
    add_doorbell_text / remove_doorbell_text services.
  fields:
    entity_id:
      name: Doorbell Text
      description: (Required) Doorbell to display message on
      example: "select.front_doorbell_camera_doorbell_text"
      required: true
      selector:
        entity:
          integration: unifiprotect
          domain: select
          device_class: unifiprotect__lcd_message
    message:
      name: Message to display
      description: (Required) Message to display on LCD Panel. Max 30 characters
      example: "Welcome | 09:23 | 25Â°C"
      required: true
      selector:
        text:
    duration:
      name: Duration (minutes)
      description: "(Optional) Number of minutes to display message, before returning to default. Leave blank to display always"
      example: 5
      selector:
        number:
          min: 1
          max: 120
          step: 1
          mode: slider
