clean_room:
  name: Clean Room
  description: Cleans a specific user-defined room or set of rooms.
  target:
    entity:
      integration: "sharkiq"
      domain: "vacuum"

  fields:
    rooms:
      name: Rooms
      description: List of rooms to clean
      required: true
      advanced: false
      example: "Kitchen"
      default: ""
      selector:
        area:
          multiple: true
