# Describes the format for available opentherm_gw services

reset_gateway:
  description: Reset the OpenTherm Gateway.
  fields:
    gateway_id:
      description: The gateway_id of the OpenTherm Gateway.
      example: "opentherm_gateway"

set_clock:
  description: Set the clock and day of the week on the connected thermostat.
  fields:
    gateway_id:
      description: The gateway_id of the OpenTherm Gateway.
      example: "opentherm_gateway"
    date:
      description: Optional date from which the day of the week will be extracted. Defaults to today.
      example: "2018-10-23"
    time:
      description: Optional time in 24h format which will be provided to the thermostat. Defaults to the current time.
      example: "19:34"

set_control_setpoint:
  description: >
    Set the central heating control setpoint override on the gateway.
    You will only need this if you are writing your own software thermostat.
  fields:
    gateway_id:
      description: The gateway_id of the OpenTherm Gateway.
      example: "opentherm_gateway"
    temperature:
      description: >
        The central heating setpoint to set on the gateway.
        Values between 0 and 90 are accepted, but not all boilers support this range.
        A value of 0 disables the central heating setpoint override.
      example: "37.5"

set_hot_water_ovrd:
  description: >
    Set the domestic hot water enable option on the gateway.
  fields:
    gateway_id:
      description: The gateway_id of the OpenTherm Gateway.
      example: "opentherm_gateway"
    dhw_override:
      description: >
        Control the domestic hot water enable option. If the boiler has
        been configured to let the room unit control when to keep a
        small amount of water preheated, this command can influence
        that.
        Value should be 0 or 1 to enable the override in off or on
        state, or "A" to disable the override.
      example: "1"

set_gpio_mode:
  description: Change the function of the GPIO pins of the gateway.
  fields:
    gateway_id:
      description: The gateway_id of the OpenTherm Gateway.
      example: "opentherm_gateway"
    id:
      description: The ID of the GPIO pin. Either "A" or "B".
      example: "B"
    mode:
      description: >
        Mode to set on the GPIO pin. Values 0 through 6 are accepted for both GPIOs, 7 is only accepted for GPIO "B".
        See https://www.home-assistant.io/integrations/opentherm_gw/#gpio-modes for an explanation of the values.
      example: "5"

set_led_mode:
  description: Change the function of the LEDs of the gateway.
  fields:
    gateway_id:
      description: The gateway_id of the OpenTherm Gateway.
      example: "opentherm_gateway"
    id:
      description: The ID of the LED. Possible values are "A" through "F".
      example: "C"
    mode:
      description: >
        The function to assign to the LED. One of "R", "X", "T", "B", "O", "F", "H", "W", "C", "E", "M" or "P".
        See https://www.home-assistant.io/integrations/opentherm_gw/#led-modes for an explanation of the values.
      example: "F"

set_max_modulation:
  description: >
    Override the maximum relative modulation level.
    You will only need this if you are writing your own software thermostat.
  fields:
    gateway_id:
      description: The gateway_id of the OpenTherm Gateway.
      example: "opentherm_gateway"
    level:
      description: >
        The modulation level to provide to the gateway.
        Values between 0 and 100 will set the modulation level.
        Provide a value of -1 to clear the override and forward the value from the thermostat again.
      example: "42"

set_outside_temperature:
  description: >
    Provide an outside temperature to the thermostat.
    If your thermostat is unable to display an outside temperature and does not support OTC (Outside Temperature Correction), this has no effect.
  fields:
    gateway_id:
      description: The gateway_id of the OpenTherm Gateway.
      example: "opentherm_gateway"
    temperature:
      description: >
        The temperature to provide to the thermostat.
        Values between -40.0 and 64.0 will be accepted, but not all thermostats can display the full range.
        Any value above 64.0 will clear a previously configured value (suggestion: 99)
      example: "-2.3"

set_setback_temperature:
  description: Configure the setback temperature to be used with the GPIO away mode function.
  fields:
    gateway_id:
      description: The gateway_id of the OpenTherm Gateway.
      example: "opentherm_gateway"
    temperature:
      description: The setback temperature to configure on the gateway. Values between 0.0 and 30.0 are accepted.
      example: "16.0"
