# Describes the format for available timer services

start:
  description: Start a timer.

  fields:
    entity_id:
      description: Entity id of the timer to start. [optional]
      example: "timer.timer0"
    duration:
      description: Duration the timer requires to finish. [optional]
      example: "00:01:00 or 60"

pause:
  description: Pause a timer.

  fields:
    entity_id:
      description: Entity id of the timer to pause. [optional]
      example: "timer.timer0"

cancel:
  description: Cancel a timer.

  fields:
    entity_id:
      description: Entity id of the timer to cancel. [optional]
      example: "timer.timer0"

finish:
  description: Finish a timer.

  fields:
    entity_id:
      description: Entity id of the timer to finish. [optional]
      example: "timer.timer0"
