# Describes the format for available services for bmw_connected_drive
#
# The services related to locking/unlocking are implemented in the lock
# component to avoid redundancy.

light_flash:
  name: Flash lights
  description: >
    Flash the lights of the vehicle. The vehicle is identified either via its
    device entry or the VIN. If a VIN is specified, the device entry will be ignored.
  fields:
    device_id:
      name: Car
      description: The BMW Connected Drive device
      selector:
        device:
          integration: bmw_connected_drive
    vin:
      name: VIN
      description: The vehicle identification number (VIN) of the vehicle, 17 characters
      advanced: true
      required: false
      example: WBANXXXXXX1234567
      selector:
        text:

sound_horn:
  name: Sound horn
  description: >
    Sound the horn of the vehicle. The vehicle is identified either via its
    device entry or the VIN. If a VIN is specified, the device entry will be ignored.
  fields:
    device_id:
      name: Car
      description: The BMW Connected Drive device
      selector:
        device:
          integration: bmw_connected_drive
    vin:
      name: VIN
      description: The vehicle identification number (VIN) of the vehicle, 17 characters
      advanced: true
      required: false
      example: WBANXXXXXX1234567
      selector:
        text:

activate_air_conditioning:
  name: Activate air conditioning
  description: >
    Start the air conditioning of the vehicle. What exactly is started here
    depends on the type of vehicle. It might range from just ventilation over
    auxiliary heating to real air conditioning. The vehicle is identified either via its
    device entry or the VIN. If a VIN is specified, the device entry will be ignored.
  fields:
    device_id:
      name: Car
      description: The BMW Connected Drive device
      selector:
        device:
          integration: bmw_connected_drive
    vin:
      name: VIN
      description: The vehicle identification number (VIN) of the vehicle, 17 characters
      advanced: true
      required: false
      example: WBANXXXXXX1234567
      selector:
        text:

find_vehicle:
  name: Find vehicle
  description: >
    Request vehicle to update the GPS location. The vehicle is identified either via its
    device entry or the VIN. If a VIN is specified, the device entry will be ignored.
  fields:
    device_id:
      name: Car
      description: The BMW Connected Drive device
      selector:
        device:
          integration: bmw_connected_drive
    vin:
      name: VIN
      description: The vehicle identification number (VIN) of the vehicle, 17 characters
      advanced: true
      required: false
      example: WBANXXXXXX1234567
      selector:
        text:

update_state:
  name: Update state
  description: >
    Fetch the last state of the vehicles of all your accounts from the BMW
    server. This does *not* trigger an update from the vehicle, it just gets
    the data from the BMW servers. This service does not require any attributes.
