# Describes the format for available services for bmw_connected_drive
#
# The services related to locking/unlocking are implemented in the lock
# component to avoid redundancy.

light_flash:
  description: >
    Flash the lights of the vehicle. The vehicle is identified via the vin
    (see below).
  fields:
    vin:
      description: >
        The vehicle identification number (VIN) of the vehicle, 17 characters
      example: WBANXXXXXX1234567

sound_horn:
  description: >
    Sound the horn of the vehicle. The vehicle is identified via the vin
    (see below).
  fields:
    vin:
      description: >
        The vehicle identification number (VIN) of the vehicle, 17 characters
      example: WBANXXXXXX1234567

activate_air_conditioning:
  description: >
    Start the air conditioning of the vehicle. What exactly is started here
    depends on the type of vehicle. It might range from just ventilation over
    auxilary heating to real air conditioning. The vehicle is identified via
    the vin (see below).
  fields:
    vin:
      description: >
        The vehicle identification number (VIN) of the vehicle, 17 characters
      example: WBANXXXXXX1234567

update_state:
  description: >
    Fetch the last state of the vehicles of all your accounts from the BMW
    server. This does *not* trigger an update from the vehicle, it just gets
    the data from the BMW servers. This service does not require any attributes.