# Describes the format for available switch services

turn_on:
  description: Turn a switch on

  fields:
    entity_id:
      description: Name(s) of entities to turn on
      example: 'switch.living_room'

turn_off:
  description: Turn a switch off

  fields:
    entity_id:
      description: Name(s) of entities to turn off
      example: 'switch.living_room'

toggle:
  description: Toggles a switch state

  fields:
    entity_id:
      description: Name(s) of entities to toggle
      example: 'switch.living_room'

mysensors_send_ir_code:
  description: Set an IR code as a state attribute for a MySensors IR device switch and turn the switch on.

  fields:
    entity_id:
      description: Name(s) of entities that should have the IR code set and be turned on. Platform dependent.
      example: 'switch.living_room_1_1'

    V_IR_SEND:
      description: IR code to send
      example: '0xC284'
