# Describes the format for available vacuum services

turn_on:
  target:
    entity:
      domain: vacuum
      supported_features:
        - vacuum.VacuumEntityFeature.TURN_ON

turn_off:
  target:
    entity:
      domain: vacuum
      supported_features:
        - vacuum.VacuumEntityFeature.TURN_OFF

stop:
  target:
    entity:
      domain: vacuum
      supported_features:
        - vacuum.VacuumEntityFeature.STOP

locate:
  target:
    entity:
      domain: vacuum
      supported_features:
        - vacuum.VacuumEntityFeature.LOCATE

start_pause:
  target:
    entity:
      domain: vacuum
      supported_features:
        - vacuum.VacuumEntityFeature.PAUSE

start:
  target:
    entity:
      domain: vacuum
      supported_features:
        - vacuum.VacuumEntityFeature.START

pause:
  target:
    entity:
      domain: vacuum
      supported_features:
        - vacuum.VacuumEntityFeature.PAUSE

return_to_base:
  target:
    entity:
      domain: vacuum
      supported_features:
        - vacuum.VacuumEntityFeature.RETURN_HOME

clean_spot:
  target:
    entity:
      domain: vacuum

send_command:
  target:
    entity:
      domain: vacuum
  fields:
    command:
      required: true
      example: "set_dnd_timer"
      selector:
        text:
    params:
      example: '{ "key": "value" }'
      selector:
        object:

set_fan_speed:
  target:
    entity:
      domain: vacuum
  fields:
    fan_speed:
      required: true
      example: "low"
      selector:
        text:
