homeassistant:
  customize_glob: !include customize_glob.yaml
  packages: !include_dir_named ais_packages/
  auth_providers:
  - type: trusted_networks
    trusted_networks:
    - 127.0.0.1
    - 0.0.0.0/0
  - type: homeassistant
  - type: legacy_api_password
    api_password: dom
  whitelist_external_dirs:
  - /data/data/pl.sviete.dom/files/home/AIS/
  - /data/data/pl.sviete.dom/files/home/AIS/www/

#
system_health:

# Track the sun
sun:

# ais-dom cloud functionality
ais_cloud:
ais_ai_service:
ais_knowledge_service:
ais_shell_command:
ais_yt_service:
ais_updater:
  include_used_components: false
ais_drives_service:

# Enables a map showing the location of tracked devices
map:

#
media_extractor:

# Enables the frontend
frontend:
  # development_repo: /home/andrzej/Projects/AIS-home-assistant-polymer
  themes: !include_dir_merge_named themes


# Enables configuration UI
config:

http:
   base_url: localhost:8180
   server_port: 8180

# AIS Service for AI
# Allows you to issue voice commands
mqtt: !include mqtt.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# bookmarks and favorites
ais_bookmarks:

# set up Zeroconf and make AIS dom discoverable
ais_mdns:

#
# ais_gm_service:
#
ais_audiobooks_service:
#
ais_spotify_service:
ais_wifi_service:

#
ais_amplifier_service:

#
person:

# TODO
# check if user is authenticated and add this to polymer
# /api/ingress/
#ais_ingress:
#  host: localhost
#  port: 8888

ais_help:
ais_virtual_devices:

conversation:
scene:
mobile_app:
ais_usb:

zone:

logger:
  default: info
