enable_output:
  description: Enable or disable an output port
  fields:
    entity_id:
      description: Name(s) of entities to enable/disable port on.
      example: 'media_player.yamaha'
    port:
      description: Name of port to enable/disable.
      example: 'hdmi1'
    enabled:
      description: Boolean indicating if port should be enabled or not.
      example: true