apply:
  description: Applies the current Adaptive Lighting settings to lights.
  fields:
    entity_id:
      description: entity_id of the Adaptive Lighting switch.
      example: switch.adaptive_lighting_default
    lights:
      description: entity_id(s) of lights.
      example: light.bedroom_ceiling
    transition:
      description: Transition of the lights.
      example: 10
    adapt_brightness:
      description: "Adapt the 'brightness', default: true"
      example: true
    adapt_color:
      description: "Adapt the color_temp/color_rgb, default: true"
      example: true
    prefer_rgb_color:
      description: "Prefer to use color_rgb over color_temp if possible, default: false"
      example: false
    turn_on_lights:
      description: "Turn on the lights that are off, default: false"
      example: false
set_manual_control:
  description: Mark whether a light is 'manually controlled'.
  fields:
    entity_id:
      description: entity_id of the Adaptive Lighting switch.
      example: switch.adaptive_lighting_default
    manual_control:
      description: "Whether to add ('true') or remove ('false') the light from the 'manual_control' list, default: true"
      example: true
    lights:
      description: entity_id(s) of lights, if not specified, all lights in the switch are selected.
      example: light.bedroom_ceiling
