boost_heating:
  name: Boost Heating
  description: Set the boost mode ON defining the period of time and the desired target temperature for the boost.
  fields:
    entity_id:
      name: Entity ID
      description: Select entity_id to boost.
      required: true
      example: climate.heating
      selector:
        entity:
          integration: hive
          domain: climate
    time_period:
      name: Time Period
      description: Set the time period for the boost.
      required: true
      example: 01:30:00
      selector:
        time:
    temperature:
      name: Temperature
      description: Set the target temperature for the boost period.
      required: true
      example: 20.5
      selector:
        number:
          min: 7
          max: 35
          step: 0.5
          unit_of_measurement: degrees
          mode: slider
boost_hot_water:
  name: Boost Hotwater
  description: Set the boost mode ON or OFF defining the period of time for the boost.
  fields:
    entity_id:
      name: Entity ID
      description: Select entity_id to boost.
      required: true
      example: water_heater.hot_water
      selector:
        entity:
          integration: hive
          domain: water_heater
    time_period:
      name: Time Period
      description: Set the time period for the boost.
      required: true
      example: 01:30:00
      selector:
        time:
    on_off:
      name: Mode
      description: Set the boost function on or off.
      required: true
      example: "on"
      selector:
        select:
          options:
            - "on"
            - "off"
