ac_start:
  description: Start A/C on vehicle.
  fields:
    vin:
      description: VIN of vehicle that will have the A/C started.
      example: "VF1xxxxxxxxxxxxxx"
    temperature:
      description: Target A/C temperature in Â°C.
      example: "21"
    when:
      description: Timestamp for the start of the A/C (optional - defaults to now).
      example: "2020-05-01T17:45:00"

ac_cancel:
  description: Cancel A/C on vehicle.
  fields:
    vin:
      description: VIN of vehicle that will have the A/C cancelled.
      example: "VF1xxxxxxxxxxxxxx"

charge_set_schedules:
  description: Update charge schedule on vehicle.
  fields:
    vin:
      description: VIN of vehicle that will have the charge schedule updated.
      example: "VF1xxxxxxxxxxxxxx"
    schedules:
      description: Schedule details.
      example: >-
        [
          {
            'id':1,
            'activated':true,
            'monday':{'startTime':'T12:00Z','duration':15},
            'tuesday':{'startTime':'T12:00Z','duration':15},
            'wednesday':{'startTime':'T12:00Z','duration':15},
            'thursday':{'startTime':'T12:00Z','duration':15},
            'friday':{'startTime':'T12:00Z','duration':15},
            'saturday':{'startTime':'T12:00Z','duration':15},
            'sunday':{'startTime':'T12:00Z','duration':15}
          },
          {
            'id':2,
            'activated':false,
            'monday':{'startTime':'T12:00Z','duration':240},
            'tuesday':{'startTime':'T12:00Z','duration':240},
            'wednesday':{'startTime':'T12:00Z','duration':240},
            'thursday':{'startTime':'T12:00Z','duration':240},
            'friday':{'startTime':'T12:00Z','duration':240},
            'saturday':{'startTime':'T12:00Z','duration':240},
            'sunday':{'startTime':'T12:00Z','duration':240}
          },
        ]

charge_start:
  description: Start charge on vehicle.
  fields:
    vin:
      description: VIN of vehicle that will have the charge started.
      example: "VF1xxxxxxxxxxxxxx"
