ac_start:
  description: Start A/C on vehicle.
  fields:
    vin:
      description: VIN of vehicle that will have the A/C started.
      example: "VF1xxxxxxxxxxxxxx"
    when:
      description: Number of seconds to set the timer (optional - defaults to now).
      example: "2020-05-01T17:45:00"
    temperature:
      description: Target A/C temperature in Â°C (optional - defaults to 21).
      example: "21"

ac_cancel:
  description: Cancel A/C on vehicle.
  fields:
    vin:
      description: VIN of vehicle that will have the A/C cancelled.
      example: "VF1xxxxxxxxxxxxxx"

charge_start:
  description: Start charge on vehicle.
  fields:
    vin:
      description: VIN of vehicle that will have the charge started.
      example: "VF1xxxxxxxxxxxxxx"

charge_set_mode:
  description: Set charge mode on vehicle.
  fields:
    vin:
      description: VIN of vehicle that will have the charge mode updated.
      example: "VF1xxxxxxxxxxxxxx"
    charge_mode:
      description: Charge mode to apply.
      example: "always or always_charging or schedule_mode"

charge_set_schedules:
  description: Update charge schedule on vehicle.
  fields:
    vin:
      description: VIN of vehicle that will have the charge schedule updated.
      example: "VF1xxxxxxxxxxxxxx"
    schedules:
      description: Schedule details.
      example: "{'id':1,'activated':true,'monday':{'startTime':'T12:00Z','duration':15},'tuesday':{'startTime':'T12:00Z','duration':15},'wednesday':{'startTime':'T12:00Z','duration':15},'thursday':{'startTime':'T12:00Z','duration':15},'friday':{'startTime':'T12:00Z','duration':15},'saturday':{'startTime':'T12:00Z','duration':15},'sunday':{'startTime':'T12:00Z','duration':15}}"
