add_url:
  description: Add a new filter subscription to AdGuard Home.
  fields:
    name:
      description: The name of the filter subscription.
      example: Example
    url:
      description: The filter URL to subscribe to, containing the filter rules.
      example: https://www.example.com/filter/1.txt

remove_url:
  description: Removes a filter subscription from AdGuard Home.
  fields:
    url:
      description: The filter subscription URL to remove.
      example: https://www.example.com/filter/1.txt

enable_url:
  description: Enables a filter subscription in AdGuard Home.
  fields:
    url:
      description: The filter subscription URL to enable.
      example: https://www.example.com/filter/1.txt

disable_url:
  description: Disables a filter subscription in AdGuard Home.
  fields:
    url:
      description: The filter subscription URL to disable.
      example: https://www.example.com/filter/1.txt

refresh:
  description: Refresh all filter subscriptions in AdGuard Home.
  fields:
    force:
      description: Force update (by passes AdGuard Home throttling).
      example: '"true" to force, "false" or omit for a regular refresh.'
