send_command:
  description: Emulate button press for PlayStation 4.
  fields:
    entity_id:
      description: Name(s) of entities to send command.
      example: "media_player.playstation_4"
    command:
      description: Button to press.
      example: "ps"
