send_command:
  name: Send command
  description: Emulate button press for PlayStation 4.
  fields:
    entity_id:
      name: Entity
      description: Name of entity to send command.
      required: true
      example: "media_player.playstation_4"
      selector:
        entity:
          integration: ps4
          domain: media_player
    command:
      name: Command
      description: Button to press.
      required: true
      example: "ps"
      selector:
        select:
          options:
            - "ps"
            - "ps_hold"
            - "option"
            - "enter"
            - "back"
            - "up"
            - "down"
            - "left"
            - "right"
