update:
  description: Updates the list of conversations.

send_message:
  description: Send a notification to a specific target.
  fields:
    target:
      description: List of targets with id or name. [Required]
      example: '[{"id": "UgxrXzVrARmjx_C6AZx4AaABAagBo-6UCw"}, {"name": "Test Conversation"}]'
    message:
      description: List of message segments, only the "text" field is required in every segment. [Required]
      example: '[{"text":"test", "is_bold": false, "is_italic": false, "is_strikethrough": false, "is_underline": false, "parse_str": false, "link_target": "http://google.com"}]'
    data:
      description: Other options ['image_file' / 'image_url']
      example: '{ "image_file": "file" }'

reconnect:
  description: Reconnect the bot.
