set_datetime:
  description: This can be used to dynamically set the date and/or time
  target:
  fields:
    date:
      name: Date
      description: The target date the entity should be set to.
      example: '"2019-04-20"'
      selector:
        text:
    time:
      name: Time
      description: The target time the entity should be set to.
      example: '"05:04:20"'
      selector:
        time:
    datetime:
      name: Date & Time
      description: The target date & time the entity should be set to.
      example: '"2019-04-20 05:04:20"'
      selector:
        text:
    timestamp:
      name: Timestamp
      description:
        The target date & time the entity should be set to as expressed by a
        UNIX timestamp.
      example: 1598027400
      selector:
        number:
          min: 0
          max: 9223372036854775807
          mode: box

reload:
  description: Reload the input_datetime configuration
