# Describes the format for available water_heater services

set_away_mode:
  target:
    entity:
      domain: water_heater
  fields:
    away_mode:
      required: true
      selector:
        boolean:

set_temperature:
  target:
    entity:
      domain: water_heater
      supported_features:
        - water_heater.WaterHeaterEntityFeature.TARGET_TEMPERATURE
        - water_heater.WaterHeaterEntityFeature.TARGET_TEMPERATURE_RANGE
  fields:
    temperature:
      filter:
        supported_features:
          - water_heater.WaterHeaterEntityFeature.TARGET_TEMPERATURE
      required: true
      selector:
        number:
          min: 0
          max: 250
          step: 0.5
          mode: box
          unit_of_measurement: "°"
    target_temp_high:
      filter:
        supported_features:
          - water_heater.WaterHeaterEntityFeature.TARGET_TEMPERATURE_RANGE
      advanced: true
      selector:
        number:
          min: 0
          max: 250
          step: 0.1
          mode: box
          unit_of_measurement: "°"
    target_temp_low:
      filter:
        supported_features:
          - water_heater.WaterHeaterEntityFeature.TARGET_TEMPERATURE_RANGE
      advanced: true
      selector:
        number:
          min: 0
          max: 250
          step: 0.1
          mode: box
          unit_of_measurement: "°"
    operation_mode:
      example: eco
      selector:
        text:

set_operation_mode:
  target:
    entity:
      domain: water_heater
  fields:
    operation_mode:
      required: true
      example: eco
      selector:
        text:

turn_on:
  target:
    entity:
      domain: water_heater

turn_off:
  target:
    entity:
      domain: water_heater
