# Describes the format for available notification services

notify:
  name: Send a notification
  description: Sends a notification message to selected notify platforms.
  fields:
    message:
      name: Message
      description: Message body of the notification.
      required: true
      example: The garage door has been open for 10 minutes.
      selector:
        text:
    title:
      name: Title
      description: Title for your notification.
      example: "Your Garage Door Friend"
      selector:
        text:
    target:
      description:
        An array of targets to send the notification to. Optional depending on
        the platform.
      example: platform specific
      selector:
        object:
    data:
      name: Data
      description:
        Extended information for notification. Optional depending on the
        platform.
      example: platform specific
      selector:
        object:

persistent_notification:
  name: Send a persistent notification
  description: Sends a notification to the visible in the front-end.
  fields:
    message:
      description: Message body of the notification.
      required: true
      example: The garage door has been open for 10 minutes.
      selector:
        text:
    title:
      description: Title for your notification.
      example: "Your Garage Door Friend"
      selector:
        text:

apns_register:
  name: Register APNS device
  description:
    Registers a device to receive push notifications via APNS (Apple Push
    Notification Service).
  fields:
    push_id:
      name: Push ID
      description:
        The device token, a 64 character hex string (256 bits). The device token
        is provided to you by your client app, which receives the token after
        registering itself with the remote notification service.
      example: "72f2a8633655c5ce574fdc9b2b34ff8abdfc3b739b6ceb7a9ff06c1cbbf99f62"
      selector:
        text:
    name:
      name: Name
      description: A friendly name for the device.
      example: "Sam's iPhone"
      selector:
        text:
