# Describes the format for available switch services

reset:
  description: Resets the counter of an utility meter.
  fields:
    entity_id:
      description: Name(s) of the utility meter to reset
      example: 'utility_meter.energy'

next_tariff:
  description: Changes the tariff to the next one.
  fields:
    entity_id:
      description: Name(s) of entities to reset
      example: 'utility_meter.energy'

select_tariff:
  description: selects the current tariff of an utility meter.
  fields:
    entity_id:
      description: Name of the entity to set the tariff for
      example: 'utility_meter.energy'
    tariff:
      description: Name of the tariff to switch to
      example: 'offpeak'

calibrate:
  description: calibrates an utility meter.
  fields:
    entity_id:
      description: Name of the entity to calibrate
      example: 'utility_meter.energy'
    value:
      description: Value to which set the meter
      example: '100'