# Describes the format for available Android TV and Fire TV services

adb_command:
  name: ADB command
  description: Send an ADB command to an Android TV / Fire TV device.
  fields:
    entity_id:
      description: Name(s) of Android TV / Fire TV entities.
      required: true
      example: "media_player.android_tv_living_room"
      selector:
        entity:
          integration: androidtv
          domain: media_player
    command:
      name: Command
      description: Either a key command or an ADB shell command.
      required: true
      example: "HOME"
      selector:
        text:
download:
  name: Download
  description: Download a file from your Android TV / Fire TV device to your Home Assistant instance.
  fields:
    entity_id:
      description: Name of Android TV / Fire TV entity.
      required: true
      example: "media_player.android_tv_living_room"
      selector:
        entity:
          integration: androidtv
          domain: media_player
    device_path:
      name: Device path
      description: The filepath on the Android TV / Fire TV device.
      required: true
      example: "/storage/emulated/0/Download/example.txt"
      selector:
        text:
    local_path:
      name: Local path
      description: The filepath on your Home Assistant instance.
      required: true
      example: "/config/www/example.txt"
      selector:
        text:
upload:
  name: Upload
  description: Upload a file from your Home Assistant instance to an Android TV / Fire TV device.
  fields:
    entity_id:
      description: Name(s) of Android TV / Fire TV entities.
      required: true
      example: "media_player.android_tv_living_room"
      selector:
        entity:
          integration: androidtv
          domain: media_player
    device_path:
      name: Device path
      description: The filepath on the Android TV / Fire TV device.
      required: true
      example: "/storage/emulated/0/Download/example.txt"
      selector:
        text:
    local_path:
      name: Local path
      description: The filepath on your Home Assistant instance.
      required: true
      example: "/config/www/example.txt"
      selector:
        text:
learn_sendevent:
  name: Learn sendevent
  description: Translate a key press on a remote into ADB 'sendevent' commands.  You must press one button on the remote within 8 seconds of calling this service.
  target:
    entity:
      integration: androidtv
      domain: media_player
