# Describes the format for available Netatmo services
set_camera_light:
  name: Set camera light mode
  description: Sets the light mode for a Netatmo Outdoor camera light.
  target:
    entity:
      integration: netatmo
      domain: light
  fields:
    camera_light_mode:
      name: Camera light mode
      description: Outdoor camera light mode (on/off/auto)
      example: auto
      required: true
      selector:
        select:
          options:
            - "on"
            - "off"
            - "auto"

set_schedule:
  name: Set heating schedule
  description: Set the heating schedule for Netatmo climate device. The schedule name must match a schedule configured at Netatmo.
  target:
    entity:
      integration: netatmo
      domain: climate
  fields:
    schedule_name:
      description: Schedule name
      example: Standard
      required: true
      selector:
        text:

set_persons_home:
  name: Set persons at home
  description: Set a list of persons as at home. Person's name must match a name known by the Netatmo Indoor (Welcome) Camera.
  target:
    entity:
      integration: netatmo
      domain: camera
  fields:
    persons:
      description: List of names
      example: Bob
      required: true
      selector:
        text:

set_person_away:
  name: Set person away
  description: Set a person as away. If no person is set the home will be marked as empty. Person's name must match a name known by the Netatmo Indoor (Welcome) Camera.
  target:
    entity:
      integration: netatmo
      domain: camera
  fields:
    person:
      description: Person's name (optional)
      example: Bob
      selector:
        text:

register_webhook:
  name: Register webhook
  description: Register the webhook to the Netatmo backend.

unregister_webhook:
  name: Unregister webhook
  description: Unregister the webhook from the Netatmo backend.
