request_sync:
  description: Send a request_sync command to Google.
  fields:
    agent_user_id:
      description: Optional. Only needed for automations. Specific Home Assistant user id to sync with Google Assistant. Do not need when you call this service through Home Assistant front end or API. Used in automation script or other place where context.user_id is missing.
