navigate_url:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: kiosker
    url:
      required: true
      selector:
        text:

navigate_refresh:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: kiosker

navigate_home:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: kiosker

navigate_backward:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: kiosker

navigate_forward:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: kiosker

print:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: kiosker

clear_cookies:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: kiosker

clear_cache:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: kiosker

screensaver_interact:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: kiosker

blackout_set:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: kiosker
    visible:
      default: true
      selector:
        boolean:
    text:
      default: "Hello, World!"
      selector:
        text:
    background:
      selector:
        color_rgb:
    foreground:
      selector:
        color_rgb:
    icon:
      selector:
        text:
    expire:
      default: 60
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    dismissible:
      selector:
        boolean:
    button_background:
      selector:
        color_rgb:
    button_foreground:
      selector:
        color_rgb:
    button_text:
      selector:
        text:
    sound:
      selector:
        text:

blackout_clear:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: kiosker

update:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: kiosker
