navigate_url:
  target:
    device:
      integration: kiosker
  fields:
    url:
      required: true
      selector:
        text:

navigate_refresh:
  target:
    device:
      integration: kiosker

navigate_home:
  target:
    device:
      integration: kiosker

navigate_backward:
  target:
    device:
      integration: kiosker

navigate_forward:
  target:
    device:
      integration: kiosker

print:
  target:
    device:
      integration: kiosker

clear_cookies:
  target:
    device:
      integration: kiosker

clear_cache:
  target:
    device:
      integration: kiosker

screensaver_interact:
  target:
    device:
      integration: kiosker

blackout_set:
  target:
    device:
      integration: kiosker
  fields:
    visible:
      selector:
        boolean:
    text:
      selector:
        text:
    background:
      selector:
        color_rgb:
    foreground:
      selector:
        color_rgb:
    icon:
      selector:
        text:
    expire:
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    dismissible:
      selector:
        boolean:
    button_background:
      selector:
        color_rgb:
    button_foreground:
      selector:
        color_rgb:
    button_text:
      selector:
        text:
    sound:
      selector:
        number:
          min: 0
          max: 9999

blackout_clear:
  target:
    device:
      integration: kiosker
