add_all_link:
  description: Tells the Insteom Modem (IM) start All-Linking mode. Once the the IM is in All-Linking mode, press the link button on the device to complete All-Linking.
  fields:
    group:
      description: All-Link group number.
      example: 1
    mode:
      description: Linking mode   controller - IM is controller   responder - IM is responder
      example: 'controller'
delete_all_link:
  description: Tells the Insteon Modem (IM) to remove an All-Link record from the All-Link Database of the IM and a device. Once the IM is set to delete the link, press the link button on the corresponding device to complete the process.
  fields:
    group:
      description: All-Link group number.
      example: 1
load_all_link_database:
  description: Load the All-Link Database for a device. WARNING - Loading a device All-LInk database is very time consuming and inconsistant. This may take a LONG time and may need to be repeated to obtain all records.
  fields:
    entity_id:
      description: Name of the device to print
      example: 'light.1a2b3c'
    reload:
      description: Reload all records. If true the current records are cleared from memory (does not effect the device) and the records are reloaded. If false the existing records are left in place and only missing records are added. Default is false.
      example: 'true'
print_all_link_database:
  description: Print the All-Link Database for a device. Requires that the All-Link Database is loaded into memory.
  fields:
    entity_id:
      description: Name of the device to print
      example: 'light.1a2b3c'
print_im_all_link_database:
  description: Print the All-Link Database for the INSTEON Modem (IM).
