# Describes the format for available Flo services

set_sleep_mode:
  name: Set sleep mode
  description: Set the location into sleep mode.
  target:
    entity:
      integration: flo
      domain: switch
  fields:
    sleep_minutes:
      name: Sleep minutes
      description: The time to sleep in minutes.
      default: true
      example: 120
      selector:
        select:
          options:
            - '120'
            - '1440'
            - '4320'
    revert_to_mode:
      name: Revert to mode
      description: The mode to revert to after sleep_minutes has elapsed.
      default: true
      example: "home"
      selector:
        select:
          options:
            - 'away'
            - 'home'
set_away_mode:
  name: Set away mode
  description: Set the location into away mode.
  target:
    entity:
      integration: flo
      domain: switch
set_home_mode:
  name: Set home mode
  description: Set the location into home mode.
  target:
    entity:
      integration: flo
      domain: switch
run_health_test:
  name: Run health test
  description: Have the Flo device run a health test.
  target:
    entity:
      integration: flo
      domain: switch
