join:
  name: Join group
  description: Group player together.
  fields:
    master:
      name: Master
      description:
        Entity ID of the player that should become the coordinator of the group.
      example: "media_player.living_room_sonos"
      selector:
        entity:
          integration: sonos
          domain: media_player
    entity_id:
      name: Entity
      description: Name of entity that will join the master.
      example: "media_player.living_room_sonos"
      selector:
        entity:
          integration: sonos
          domain: media_player

unjoin:
  name: Unjoin group
  description: Unjoin the player from a group.
  fields:
    entity_id:
      name: Entity
      description: Name of entity that will be unjoined from their group.
      example: "media_player.living_room_sonos"
      selector:
        entity:
          integration: sonos
          domain: media_player

snapshot:
  name: Snapshot
  description: Take a snapshot of the media player.
  fields:
    entity_id:
      name: Entity
      description: Name of entity that will be snapshot.
      example: "media_player.living_room_sonos"
      selector:
        entity:
          integration: sonos
          domain: media_player
    with_group:
      name: With group
      description: True or False. Also snapshot the group layout.
      example: "true"
      default: true
      selector:
        boolean:

restore:
  name: Restore
  description: Restore a snapshot of the media player.
  fields:
    entity_id:
      name: Entity
      description: Name of entity that will be restored.
      example: "media_player.living_room_sonos"
      selector:
        entity:
          integration: sonos
          domain: media_player
    with_group:
      name: With group
      description: True or False. Also restore the group layout.
      example: "true"
      default: true
      selector:
        boolean:

set_sleep_timer:
  name: Set timer
  description: Set a Sonos timer.
  target:
    device:
      integration: sonos
  fields:
    sleep_time:
      name: Sleep Time
      description: Number of seconds to set the timer.
      example: "900"
      selector:
        number:
          min: 0
          max: 7200
          step: 1
          unit_of_measurement: seconds
          mode: slider

clear_sleep_timer:
  name: Clear timer
  description: Clear a Sonos timer.
  target:
    device:
      integration: sonos

set_option:
  name: Set option
  description: Set Sonos sound options.
  target:
    device:
      integration: sonos
  fields:
    night_sound:
      name: Night sound
      description: Enable Night Sound mode
      example: "true"
      selector:
        boolean:
    speech_enhance:
      name: Speech enhance
      description: Enable Speech Enhancement mode
      example: "true"
      selector:
        boolean:
    status_light:
      name: Status light
      description: Enable Status (LED) Light
      example: "true"
      selector:
        boolean:

play_queue:
  name: Play queue
  description: Start playing the queue from the first item.
  target:
    device:
      integration: sonos
  fields:
    queue_position:
      name: Queue position
      description: Position of the song in the queue to start playing from.
      example: "0"
      selector:
        number:
          min: 0
          max: 10000
          mode: box

remove_from_queue:
  name: Remove from queue
  description: Removes an item from the queue.
  target:
    device:
      integration: sonos
  fields:
    queue_position:
      name: Queue position
      description: Position in the queue to remove.
      example: "0"
      selector:
        number:
          min: 0
          max: 10000
          mode: box

update_alarm:
  name: Update alarm
  description: Updates an alarm with new time and volume settings.
  target:
    device:
      integration: sonos
  fields:
    alarm_id:
      name: Alarm ID
      description: ID for the alarm to be updated.
      example: "1"
      required: true
      selector:
        number:
          min: 1
          max: 1440
          mode: box
    time:
      name: Time
      description: Set time for the alarm.
      example: "07:00"
      selector:
        time:
    volume:
      name: Volume
      description: Set alarm volume level.
      example: "0.75"
      selector:
        number:
          min: 0
          max: 1
          step: 0.01
          mode: slider
    enabled:
      name: Alarm enabled
      description: Enable or disable the alarm.
      example: "true"
      selector:
        boolean:
    include_linked_zones:
      name: Include linked zones
      description: Enable or disable including grouped rooms.
      example: "true"
      selector:
        boolean:
