# Describes the format for available Blink services

record:
  target:
    entity:
      integration: blink
      domain: camera

trigger_camera:
  target:
    entity:
      integration: blink
      domain: camera

save_video:
  target:
    entity:
      integration: blink
      domain: camera
  fields:
    filename:
      required: true
      example: "/tmp/video.mp4"
      selector:
        text:

save_recent_clips:
  target:
    entity:
      integration: blink
      domain: camera
  fields:
    file_path:
      required: true
      example: "/tmp"
      selector:
        text:
