load_url:
  name: Load URL
  description: Load a URL on Fully Kiosk Browser
  target:
    device:
      integration: fully_kiosk
  fields:
    url:
      name: URL
      description: URL to load.
      example: "https://home-assistant.io"
      required: true
      selector:
        text:

start_application:
  name: Start Application
  description: Start an application on the device running Fully Kiosk Browser.
  target:
    device:
      integration: fully_kiosk
  fields:
    application:
      name: Application
      description: Package name of the application to start.
      example: "de.ozerov.fully"
      required: true
      selector:
        text:
