set_watering_time:
  description: Set watering time
  fields:
    entity_id:
      description: Name of a irrigation valve to set watering time
      example: "switch.sprinkler_1"
    watering_time:
      description: Duration for this irrigation to be turned on
      example: 30
set_pause_time:
  description: Set pause time
  fields:
    entity_id:
      description: Name of a pause irrigation switch to set pause time
      example: "switch.sprinkler_1_pause"
    pause_time:
      description: Duration for this irrigation to be paused
      example: 24
set_trigger:
  description: Set trigger
  fields:
    entity_id:
      description: Name of a irrigation valve to set trigger
      example: "switch.wl000000000090_1_watering"
    trigger_index:
      description: Index of Trigger from 1 to 4
      example: "1"
    trigger:
      description: Configuration of trigger
      example: "00007001"
