volume_up:
  name: Volume up
  description:
    Simulates a key press of the "Volume Up" button on Home Assistant's host
    machine

volume_down:
  name: Volume down
  description:
    Simulates a key press of the "Volume Down" button on Home Assistant's host
    machine

volume_mute:
  name: Volume mute
  description:
    Simulates a key press of the "Volume Mute" button on Home Assistant's host
    machine

media_play_pause:
  name: Media play/pause
  description:
    Simulates a key press of the "Media Play/Pause" button on Home Assistant's
    host machine

media_next_track:
  name: Media next track
  description:
    Simulates a key press of the "Media Next Track" button on Home Assistant's
    host machine

media_prev_track:
  name: Media previous track
  description:
    Simulates a key press of the "Media Previous Track" button on Home
    Assistant's host machine
