set_auto_off:
  description: "Update Switcher device auto off setting."
  fields:
    entity_id:
      description: "Name of the entity id associated with the integration, used for permission validation."
      example: "switch.switcher_kis_boiler"
    auto_off:
      description: "Time period string containing hours and minutes."
      example: '"02:30"'
