# Describes the format for available AIS cloud services
cec_command:
  description: Wysłanie komendy HDMI-CEC
  fields:
    command:
      description: komenda, np. 0x40 0x04 (One Touch Play), 0x40 0x36 (System Standby),
      example: '0x40 0x04'

change_host_name:
  description: Zmiana nazwy hosta urządzenia
  fields:
    hostname:
      description: Nowa nazwa hosta
      example: 'ais-dom'

execute_command:
  description: Wykonanie komendy w konsoli
  fields:
    command:
      description: Komenda do wykonania
      example: 'touch /data/data/pl.sviete.dom/files/home/1.txt'

execute_script:
  description: Uruchomienie skryptu w konsoli
  fields:
    script:
      description: Skrypt do wykonania
      example: '/data/data/pl.sviete.dom/.ais/upgrade_ais.sh'

key_event:
  description: Symulacja naciśnięcia przycisku w systemie
  fields:
    key_code:
      description: kod przycisku
      example: 'KEYCODE_BACK'

led:
  description: Sterowanie diodą led umieszczoną z przodu urządzenia
  fields:
    brightness:
      description: Parametr do przekazania, 0 - czerwony, 255 - niebieski, timer - utuchomienie funkcji mrugania, heartbeat - uruchomienie funkcji bicia serca. Inne funkcje to (none, rc-feedback, nand-disk, oneshot, backlight, emmc, sd, sdio, breathe, scpi, scpistop, disturb, rfkill0, rfkill1).
      example: '255'

set_scaling_governor:
  description: Ustawienie trybu zarządzania częstotliwością procesora.
  fields:
    scaling:
      description: Tryb zarządzania częstotliwością procesora. Domyślnie interactive, inne możliwe wartości to hotplug i performance.
      example: 'interactive'

set_io_scheduler:
  description: Ustawienie trybu zarządzania danymi wchodzącymi i wychodzącymi
  fields:
    scheduler:
      description: Tryb zarządzania I/O. Domyślnie noop, inne możliwe wartości to deadline cfq.
      example: 'noop'

restart_pm2_service:
  description: Restart serwisu PM2 (ais, ftp, mqtt, tunnel, webssh...)
  fields:
    service:
      description: Serwis do restartu
      example: 'tunnel'