get_requests:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: overseerr
    status:
      selector:
        select:
          options:
            - approved
            - pending
            - available
            - processing
            - unavailable
            - failed
          translation_key: request_status
    sort_order:
      selector:
        select:
          options:
            - added
            - modified
          translation_key: request_sort_order
    requested_by:
      selector:
        number:
          min: 0
          mode: box

search_media:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: overseerr
    query:
      required: true
      selector:
        text:
      description: "The search query"
    limit:
      selector:
        number:
          min: 1
          mode: box
      description: "Maximum number of results to return"
