change_control_type:
  fields:
    control_type:
      required: true
      default: NO_SELECTION
      selector:
        select:
          options:
            - "NO_SELECTION"
            - "FILL_RATE_BASED_CONTROL"
trigger_and_get_schedule:
  fields:
    soc_at_start:
      required: true
      selector:
        number:

