# Describes the format for available device tracker services

see:
  description: Control tracked device.
  fields:
    mac:
      description: MAC address of device
      example: "FF:FF:FF:FF:FF:FF"
    dev_id:
      description: Id of device (find id in known_devices.yaml).
      example: "phonedave"
    host_name:
      description: Hostname of device
      example: "Dave"
    location_name:
      description: Name of location where device is located (not_home is away).
      example: "home"
    gps:
      description: GPS coordinates where device is located (latitude, longitude).
      example: "[51.509802, -0.086692]"
    gps_accuracy:
      description: Accuracy of GPS coordinates.
      example: "80"
    battery:
      description: Battery level of device.
      example: "100"
