# Describes the format for available Number entity services

set_value:
  description: Set the value of a Number entity
  target:
  fields:
    value:
      name: Value
      description: The target value the entity should be set to.
      example: 42
      selector:
        text:
