set_default_level:
  name: Set default level
  description: Set the default log level for integrations.
  fields:
    level:
      name: Level
      description: Default severity level for all integrations.
      selector:
        select:
          options:
            - debug
            - info
            - warning
            - error
            - fatal
            - critical

set_level:
  name: Set level
  description: Set log level for integrations.
  fields:
    homeassistant.core:
      name: Home Assistant Core
      description:
        "Example on how to change the logging level for a Home Assistant Core
        integrations."
      selector:
        select:
          options:
            - 'debug'
            - 'critical'
            - 'error'
            - 'fatal'
            - 'info'
            - 'warn'
            - 'warning'
    homeassistant.components.mqtt:
      name: Home Assistant components mqtt
      description:
        "Example on how to change the logging level for an Integration."
      selector:
        select:
          options:
            - 'debug'
            - 'critical'
            - 'error'
            - 'fatal'
            - 'info'
            - 'warn'
            - 'warning'
    custom_components.my_integration:
      name: Custom components "my_integation"
      description:
        "Example on how to change the logging level for a Custom Integration."
      selector:
        select:
          options:
            - 'debug'
            - 'critical'
            - 'error'
            - 'fatal'
            - 'info'
            - 'warn'
            - 'warning'
    aiohttp:
      name: aioHttp
      description:
        "Example on how to change the logging level for a Python module."
      selector:
        select:
          options:
            - 'debug'
            - 'critical'
            - 'error'
            - 'fatal'
            - 'info'
            - 'warn'
            - 'warning'
