power_on:
  name: Power on
  description: Power on all devices which supports it.
select_device:
  name: Select device
  description: Select HDMI device.
  fields:
    device:
      name: Device
      description: Address of device to select. Can be entity_id, physical address or alias from configuration.
      required: true
      example: '"switch.hdmi_1" or "1.1.0.0" or "01:10"'
      selector:
        text:
send_command:
  name: Send command
  description: Sends CEC command into HDMI CEC capable adapter.
  fields:
    att:
      name: Att
      description: Optional parameters.
      example: [0, 2]
      selector:
        object:
    cmd:
      name: Command
      description: 'Command itself. Could be decimal number or string with hexadeximal notation: "0x10".'
      example: 144 or "0x90"
      selector:
        text:
    dst:
      name: Destination
      description: 'Destination for command. Could be decimal number or string with hexadeximal notation: "0x10".'
      example: 5 or "0x5"
      selector:
        text:
    raw:
      name: Raw
      description: >-
        Raw CEC command in format "00:00:00:00" where first two digits
        are source and destination, second byte is command and optional other bytes
        are command parameters. If raw command specified, other params are ignored.
      example: '"10:36"'
      selector:
        text:
    src:
      name: Source
      description: 'Source of command. Could be decimal number or string with hexadeximal notation: "0x10".'
      example: 12 or "0xc"
      selector:
        text:
standby:
  name: Standby
  description: Standby all devices which supports it.
update:
  name: Update
  description: Update devices state from network.
volume:
  name: Volume
  description: Increase or decrease volume of system.
  fields:
    down:
      name: Down
      description: Decreases volume x levels.
      example: 3
      selector:
        number:
          min: 1
          max: 100
    mute:
      name: Mute
      description: Mutes audio system.
      example: toggle
      selector:
        select:
          options:
            - 'off'
            - 'on'
            - 'toggle'
    up:
      name: Up
      description: Increases volume x levels.
      example: 3
      selector:
        number:
          min: 1
          max: 100
